#include "pmd2_scripts_opcodes.hpp"
using namespace std;

namespace pmd2
{

//==============================================================================
//  OpCodesInfoListEoTD
//==============================================================================
    const array<OpCodeInfoEoTD, static_cast<uint16_t>(eScriptOpCodesEoTD::NBOpcodes)> OpCodesInfoListEoTD
    { {
//      { Opname,                            nbparams,  unk1, unk2, unk3 }
        { "null",                                   0, eCommandCat::Null            },
        { "back_ChangeGround",                      1, eCommandCat::SingleOp        },
        { "back_SetBackEffect",                     1, eCommandCat::SingleOp        },
        { "back_SetBackScrollOffset",               2, eCommandCat::SingleOp        },
        { "back_SetBackScrollSpeed",                2, eCommandCat::SingleOp        },
        { "back_SetBanner",                         2, eCommandCat::SingleOp        },
        { "back_SetEffect",                         2, eCommandCat::SingleOp        },
        { "back_SetDungeonBanner",                  2, eCommandCat::SingleOp        },
        { "back_SetGround",                         1, eCommandCat::SingleOp        },
        { "back_SetTitleBanner",                    2, eCommandCat::SingleOp        },
        { "back_SetWeather",                        1, eCommandCat::SingleOp        },
        { "back_SetWeatherEffect",                  1, eCommandCat::SingleOp        },
        { "back_SetWeatherScrollOffset",            2, eCommandCat::SingleOp        },
        { "back_SetWeatherScrollSpeed",             2, eCommandCat::SingleOp        },
        { "back2_SetBackEffect",                    1, eCommandCat::SingleOp        },
        { "back2_SetBackScrollOffset",              2, eCommandCat::SingleOp        },
        { "back2_SetBackScrollSpeed",               2, eCommandCat::SingleOp        },
        { "back2_SetData",                          2, eCommandCat::SingleOp        },
        { "back2_SetEffect",                        2, eCommandCat::SingleOp        },
        { "back2_SetGround",                        1, eCommandCat::SingleOp        },
        { "back2_SetMode",                          1, eCommandCat::SingleOp        },
        { "back2_SetSpecialActing",                 3, eCommandCat::SingleOp        },
        { "back2_SetWeather",                       1, eCommandCat::SingleOp        },
        { "back2_SetWeatherEffect",                 1, eCommandCat::SingleOp        },
        { "back2_SetWeatherScrollOffset",           2, eCommandCat::SingleOp        },
        { "back2_SetWeatherScrollSpeed",            2, eCommandCat::SingleOp        },
        { "bgm_FadeOut",                            1, eCommandCat::SingleOp        },
        { "bgm_Play",                               1, eCommandCat::SingleOp        },
        { "bgm_PlayFadeIn",                         3, eCommandCat::SingleOp,         { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::Duration}, {eOpParamTypes::UNK_Placeholder} } },
        { "bgm_Stop",                               0, eCommandCat::SingleOp        },
        { "bgm_ChangeVolume",                       2, eCommandCat::SingleOp        },
        { "bgm2_FadeOut",                           1, eCommandCat::SingleOp        },
        { "bgm2_Play",                              1, eCommandCat::SingleOp        },
        { "bgm2_PlayFadeIn",                        3, eCommandCat::SingleOp        },
        { "bgm2_Stop",                              0, eCommandCat::SingleOp        },
        { "bgm2_ChangeVolume",                      2, eCommandCat::SingleOp        },
        { "Branch",                                 3, eCommandCat::BranchCmd       },
        { "BranchBit",                              3, eCommandCat::BranchCmd       },
        { "BranchDebug",                            2, eCommandCat::BranchCmd       },
        { "BranchEdit",                             2, eCommandCat::BranchCmd       },
        { "BranchExecuteSub",                       2, eCommandCat::BranchCmd       },
        { "BranchPerformance",                      3, eCommandCat::BranchCmd       },
        { "BranchScenarioNow",                      4, eCommandCat::BranchCmd       },
        { "BranchScenarioNowAfter",                 4, eCommandCat::BranchCmd       },
        { "BranchScenarioNowBefore",                4, eCommandCat::BranchCmd       },
        { "BranchScenarioAfter",                    4, eCommandCat::BranchCmd       },
        { "BranchScenarioBefore",                   4, eCommandCat::BranchCmd       },
        { "BranchSum",                              4, eCommandCat::BranchCmd       },
        { "BranchValue",                            4, eCommandCat::BranchCmd       },
        { "BranchVariable",                         4, eCommandCat::BranchCmd       },
        { "BranchVariation",                        2, eCommandCat::BranchCmd       },
        { "Call",                                   1, eCommandCat::Call            },
        { "CallCommon",                             1, eCommandCat::CallCommon      },
        { "camera_Move2Default",                    1, eCommandCat::SingleOp        },
        { "camera_Move2MyPosition",                 1, eCommandCat::SingleOp        },
        { "camera_Move2Myself",                     1, eCommandCat::SingleOp        },
        { "camera_Move2PositionMark",               5, eCommandCat::SingleOp        },
        { "camera_Move3Default",                    1, eCommandCat::SingleOp        },
        { "camera_Move3MyPosition",                 1, eCommandCat::SingleOp        },
        { "camera_Move3Myself",                     1, eCommandCat::SingleOp        },
        { "camera_Move3PositionMark",               5, eCommandCat::SingleOp        },
        { "camera_MoveDefault",                     1, eCommandCat::SingleOp        },
        { "camera_MoveMyPosition",                  1, eCommandCat::SingleOp        },
        { "camera_MoveMyself",                      1, eCommandCat::SingleOp        },
        { "camera_MovePositionMark",                5, eCommandCat::SingleOp        },
        { "camera_SetDefault",                      0, eCommandCat::SingleOp        },
        { "camera_SetEffect",                       3, eCommandCat::SingleOp        },
        { "camera_SetMyPosition",                   0, eCommandCat::SingleOp        },
        { "camera_SetMyself",                       0, eCommandCat::SingleOp        },
        { "camera_SetPositionMark",                 4, eCommandCat::SingleOp        },
        { "camera2_Move2Default",                   1, eCommandCat::SingleOp        },
        { "camera2_Move2MyPosition",                1, eCommandCat::SingleOp        },
        { "camera2_Move2Myself",                    1, eCommandCat::SingleOp        },
        { "camera2_Move2PositionMark",              5, eCommandCat::SingleOp        },
        { "camera2_Move3Default",                   1, eCommandCat::SingleOp        },
        { "camera2_Move3MyPosition",                1, eCommandCat::SingleOp        },
        { "camera2_Move3Myself",                    1, eCommandCat::SingleOp        },
        { "camera2_Move3PositionMark",              5, eCommandCat::SingleOp        },
        { "camera2_MoveDefault",                    1, eCommandCat::SingleOp        },
        { "camera2_MoveMyPosition",                 1, eCommandCat::SingleOp        },
        { "camera2_MoveMyself",                     1, eCommandCat::SingleOp        },
        { "camera2_MovePositionMark",               5, eCommandCat::SingleOp        },
        { "camera2_SetDefault",                     0, eCommandCat::SingleOp        },
        { "camera2_SetEffect",                      3, eCommandCat::SingleOp        },
        { "camera2_SetMyPosition",                  0, eCommandCat::SingleOp        },
        { "camera2_SetMyself",                      0, eCommandCat::SingleOp        },
        { "camera2_SetPositionMark",                4, eCommandCat::SingleOp        },
        { "Case",                                   2, eCommandCat::Case            },
        { "CaseMenu",                               2, eCommandCat::Case            },
        { "CaseScenario",                           3, eCommandCat::Case            },
        { "CaseText",                               2, eCommandCat::Case,           { {eOpParamTypes::Integer}, {eOpParamTypes::String}, } },
        { "CaseValue",                              3, eCommandCat::Case            },
        { "CaseVariable",                           3, eCommandCat::Case            },
        { "debug_Assert",                           1, eCommandCat::SingleOp        },
        { "debug_Print",                            1, eCommandCat::SingleOp,       { {eOpParamTypes::Constant} } },
        { "debug_PrintFlag",                        2, eCommandCat::SingleOp        },
        { "debug_PrintScenario",                    2, eCommandCat::SingleOp        },
        { "DefaultText",                            1, eCommandCat::Case,           { {eOpParamTypes::String}, } },
        { "Destroy",                                0, eCommandCat::Destroy         },
        { "End",                                    0, eCommandCat::End             },
        { "ExecuteActing",                          1, eCommandCat::SingleOp        },
        { "ExecuteCommon",                          2, eCommandCat::SingleOp        },
        { "flag_CalcBit",                           3, eCommandCat::SingleOp        },
        { "flag_CalcValue",                         3, eCommandCat::SingleOp        },
        { "flag_CalcVariable",                      3, eCommandCat::SingleOp        },
        { "flag_Clear",                             1, eCommandCat::SingleOp        },
        { "flag_Initial",                           1, eCommandCat::SingleOp        },
        { "flag_Set",                               2, eCommandCat::SingleOp        },
        { "flag_ResetDungeonResult",                0, eCommandCat::SingleOp        },
        { "flag_ResetScenario",                     1, eCommandCat::SingleOp        },
        { "flag_SetAdventureLog",                   1, eCommandCat::SingleOp        },
        { "flag_SetDungeonMode",                    2, eCommandCat::SingleOp        },
        { "flag_SetDungeonResult",                  2, eCommandCat::SingleOp        },
        { "flag_SetPerformance",                    2, eCommandCat::SingleOp        },
        { "flag_SetScenario",                       3, eCommandCat::SingleOp        },
        { "Flash",                                  0, eCommandCat::SingleOp        },
        { "Hold",                                   0, eCommandCat::SingleOp        },
        { "Jump",                                   1, eCommandCat::Jump,           { {eOpParamTypes::InstructionOffset}, } },
        { "JumpCommon",                             1, eCommandCat::JumpCommon      },
        { "lives",                                  1, eCommandCat::EntityAccessor, { {eOpParamTypes::Unk_LivesRef}, } },
        { "LoadPosition",                           1, eCommandCat::SingleOp        },
        { "Lock",                                   1, eCommandCat::Lock            },
        { "main_EnterAdventure",                    2, eCommandCat::SingleOp        },
        { "main_EnterDungeon",                      2, eCommandCat::SingleOp        },
        { "main_EnterGround",                       2, eCommandCat::SingleOp        },
        { "main_EnterGroundMulti",                  3, eCommandCat::SingleOp        },
        { "main_EnterRescueUser",                   1, eCommandCat::SingleOp        },
        { "main_EnterTraining",                     2, eCommandCat::SingleOp        },
        { "main_EnterTraining2",                    2, eCommandCat::SingleOp        },
        { "main_SetGround",                         1, eCommandCat::SingleOp        },
        { "me_Play",                                1, eCommandCat::SingleOp        },
        { "me_Stop",                                0, eCommandCat::SingleOp        },
        { "message_Close",                          0, eCommandCat::SingleOp        },
        { "message_CloseEnforce",                   0, eCommandCat::SingleOp        },
        { "message_Explanation",                    1, eCommandCat::SingleOp        },
        { "message_FacePositionOffset",             2, eCommandCat::SingleOp        },
        { "message_ImitationSound",                 1, eCommandCat::SingleOp        },
        { "message_KeyWait",                        0, eCommandCat::SingleOp        },
        { "message_Mail",                           1, eCommandCat::SingleOp        },
        { "message_Menu",                           1, eCommandCat::SingleOp        },
        { "message_Monologue",                      1, eCommandCat::SingleOp        },
        { "message_Narration",                      2, eCommandCat::SingleOp        },
        { "message_Notice",                         1, eCommandCat::SingleOp        },
        { "message_EmptyActor",                     0, eCommandCat::SingleOp        },
        { "message_ResetActor",                     0, eCommandCat::SingleOp        },
        { "message_SetActor",                       1, eCommandCat::SingleOp        },
        { "message_SetFace",                        3, eCommandCat::SingleOp        },
        { "message_SetFaceEmpty",                   3, eCommandCat::SingleOp        },
        { "message_SetFaceOnly",                    3, eCommandCat::SingleOp        },
        { "message_SetFacePosition",                1, eCommandCat::SingleOp        },
        { "message_SetWaitMode",                    2, eCommandCat::SingleOp        },
        { "message_SpecialTalk",                    1, eCommandCat::SingleOp        },
        { "message_SwitchMenu",                     2, eCommandCat::Switch          },
        { "message_SwitchMonologue",                1, eCommandCat::Switch,           { {eOpParamTypes::Unk_ScriptVariable} } },
        { "message_SwitchTalk",                     1, eCommandCat::Switch          },
        { "message_Talk",                           1, eCommandCat::SingleOp        },
        { "Move2Position",                          3, eCommandCat::SingleOp        },
        { "Move2PositionLives",                     2, eCommandCat::SingleOp        },
        { "Move2PositionMark",                      5, eCommandCat::SingleOp        },
        { "Move2PositionOffset",                    3, eCommandCat::SingleOp        },
        { "Move2PositionOffsetRandom",              3, eCommandCat::SingleOp        },
        { "Move3Position",                          3, eCommandCat::SingleOp        },
        { "Move3PositionLives",                     2, eCommandCat::SingleOp        },
        { "Move3PositionMark",                      5, eCommandCat::SingleOp        },
        { "Move3PositionOffset",                    3, eCommandCat::SingleOp        },
        { "Move3PositionOffsetRandom",              3, eCommandCat::SingleOp        },
        { "MoveDirection",                          3, eCommandCat::SingleOp        },
        { "MoveHeight",                             2, eCommandCat::SingleOp        },
        { "MovePosition",                           3, eCommandCat::SingleOp        },
        { "MovePositionLives",                      2, eCommandCat::SingleOp        },
        { "MovePositionLivesTime",                  3, eCommandCat::SingleOp        },
        { "MovePositionMark",                       5, eCommandCat::SingleOp        },
        { "MovePositionMarkTime",                   6, eCommandCat::SingleOp        },
        { "MovePositionOffset",                     3, eCommandCat::SingleOp        },
        { "MoveSpecial",                            3, eCommandCat::SingleOp        },
        { "MoveTurn",                               3, eCommandCat::SingleOp        },
        { "object",                                 1, eCommandCat::EntityAccessor, { {eOpParamTypes::Unk_ObjectRef}, } },
        { "performer",                              1, eCommandCat::EntityAccessor, { {eOpParamTypes::Unk_PerformerRef}, } },
        { "ProcessSpecial",                         3, eCommandCat::SingleOp        },
        { "ResetAttribute",                         1, eCommandCat::SingleOp        },
        { "ResetFunctionAttribute",                 1, eCommandCat::SingleOp        },
        { "ResetHitAttribute",                      1, eCommandCat::SingleOp        },
        { "ResetOutputAttribute",                   1, eCommandCat::SingleOp        },
        { "ResetReplyAttribute",                    1, eCommandCat::SingleOp        },
        { "Return",                                 0, eCommandCat::Return          },
        { "SavePosition",                           1, eCommandCat::SingleOp        },
        { "screen_FadeChange",                      4, eCommandCat::SingleOp        },
        { "screen_FadeChangeAll",                   4, eCommandCat::SingleOp        },
        { "screen_FadeIn",                          2, eCommandCat::SingleOp        },
        { "screen_FadeInAll",                       2, eCommandCat::SingleOp        },
        { "screen_FadeOut",                         2, eCommandCat::SingleOp        },
        { "screen_FadeOutAll",                      2, eCommandCat::SingleOp        },
        { "screen_FlushChange",                     8, eCommandCat::SingleOp        },
        { "screen_FlushIn",                         6, eCommandCat::SingleOp        },
        { "screen_FlushOut",                        6, eCommandCat::SingleOp        },
        { "screen_WhiteChange",                     4, eCommandCat::SingleOp        },
        { "screen_WhiteChangeAll",                  4, eCommandCat::SingleOp        },
        { "screen_WhiteIn",                         2, eCommandCat::SingleOp        },
        { "screen_WhiteInAll",                      2, eCommandCat::SingleOp        },
        { "screen_WhiteOut",                        2, eCommandCat::SingleOp        },
        { "screen_WhiteOutAll",                     2, eCommandCat::SingleOp        },
        { "screen2_FadeChange",                     4, eCommandCat::SingleOp        },
        { "screen2_FadeChangeAll",                  4, eCommandCat::SingleOp        },
        { "screen2_FadeIn",                         2, eCommandCat::SingleOp        },
        { "screen2_FadeInAll",                      2, eCommandCat::SingleOp        },
        { "screen2_FadeOut",                        2, eCommandCat::SingleOp        },
        { "screen2_FadeOutAll",                     2, eCommandCat::SingleOp        },
        { "screen2_FlushChange",                    8, eCommandCat::SingleOp        },
        { "screen2_FlushIn",                        6, eCommandCat::SingleOp        },
        { "screen2_FlushOut",                       6, eCommandCat::SingleOp        },
        { "screen2_WhiteChange",                    4, eCommandCat::SingleOp        },
        { "screen2_WhiteChangeAll",                 4, eCommandCat::SingleOp        },
        { "screen2_WhiteIn",                        2, eCommandCat::SingleOp        },
        { "screen2_WhiteInAll",                     2, eCommandCat::SingleOp        },
        { "screen2_WhiteOut",                       2, eCommandCat::SingleOp        },
        { "screen2_WhiteOutAll",                    2, eCommandCat::SingleOp        },
        { "se_FadeOut",                             2, eCommandCat::SingleOp        },
        { "se_Play",                                1, eCommandCat::SingleOp        },
        { "se_Stop",                                1, eCommandCat::SingleOp        },
        { "SetAnimation",                           1, eCommandCat::SingleOp        },
        { "SetAttribute",                           1, eCommandCat::SingleOp        },
        { "SetDirection",                           1, eCommandCat::SingleOp        },
        { "SetDirectionLives",                      2, eCommandCat::SingleOp        },
        { "SetEffect",                              2, eCommandCat::SingleOp        },
        { "SetFunctionAttribute",                   1, eCommandCat::SingleOp        },
        { "SetHeight",                              1, eCommandCat::SingleOp        },
        { "SetHitAttribute",                        1, eCommandCat::SingleOp        },
        { "SetMoveRange",                           6, eCommandCat::SingleOp        },
        { "SetOutputAttribute",                     1, eCommandCat::SingleOp        },
        { "SetPosition",                            2, eCommandCat::SingleOp        },
        { "SetPositionInitial",                     0, eCommandCat::SingleOp        },
        { "SetPositionLives",                       1, eCommandCat::SingleOp        },
        { "SetPositionMark",                        4, eCommandCat::SingleOp        },
        { "SetPositionOffset",                      2, eCommandCat::SingleOp        },
        { "SetPositionOffsetRandom",                2, eCommandCat::SingleOp        },
        { "SetReplyAttribute",                      1, eCommandCat::SingleOp        },
        { "Slide2Position",                         3, eCommandCat::SingleOp        },
        { "Slide2PositionLives",                    2, eCommandCat::SingleOp        },
        { "Slide2PositionMark",                     5, eCommandCat::SingleOp        },
        { "Slide2PositionOffset",                   3, eCommandCat::SingleOp        },
        { "Slide2PositionOffsetRandom",             3, eCommandCat::SingleOp        },
        { "Slide3Position",                         3, eCommandCat::SingleOp        },
        { "Slide3PositionLives",                    2, eCommandCat::SingleOp        },
        { "Slide3PositionMark",                     5, eCommandCat::SingleOp        },
        { "Slide3PositionOffset",                   3, eCommandCat::SingleOp        },
        { "Slide3PositionOffsetRandom",             3, eCommandCat::SingleOp        },
        { "SlideHeight",                            2, eCommandCat::SingleOp        },
        { "SlidePosition",                          3, eCommandCat::SingleOp        },
        { "SlidePositionLives",                     2, eCommandCat::SingleOp        },
        { "SlidePositionLivesTime",                 3, eCommandCat::SingleOp        },
        { "SlidePositionMark",                      5, eCommandCat::SingleOp        },
        { "SlidePositionMarkTime",                  6, eCommandCat::SingleOp        },
        { "SlidePositionOffset",                    3, eCommandCat::SingleOp        },
        { "sound_FadeOut",                          1, eCommandCat::SingleOp        },
        { "sound_Stop",                             0, eCommandCat::SingleOp        },
        { "supervision_Acting",                     1, eCommandCat::SingleOp        },
        { "supervision_ExecuteActing",              3, eCommandCat::SingleOp        },
        { "supervision_ExecuteActingSub",           3, eCommandCat::SingleOp        },
        { "supervision_ExecuteCommon",              1, eCommandCat::SingleOp        },
        { "supervision_ExecuteEnter",               1, eCommandCat::SingleOp        },
        { "supervision_ExecuteStation",             3, eCommandCat::SingleOp        },
        { "supervision_ExecuteStationCommon",       2, eCommandCat::SingleOp        },
        { "supervision_ExecuteStationCommonSub",    2, eCommandCat::SingleOp        },
        { "supervision_ExecuteStationSub",          3, eCommandCat::SingleOp        },
        { "supervision_ExecuteExport",              1, eCommandCat::SingleOp        },
        { "supervision_LoadStation",                2, eCommandCat::SingleOp        },
        { "supervision_Remove",                     1, eCommandCat::SingleOp        },
        { "supervision_RemoveActing",               1, eCommandCat::SingleOp        },
        { "supervision_RemoveCommon",               1, eCommandCat::SingleOp        },
        { "supervision_SpecialActing",              3, eCommandCat::SingleOp        },
        { "supervision_Station",                    1, eCommandCat::SingleOp        },
        { "supervision_StationCommon",              1, eCommandCat::SingleOp        },
        { "supervision_Suspend",                    1, eCommandCat::SingleOp        },
        { "supervision2_SpecialActing",             3, eCommandCat::SingleOp        },
        { "Switch",                                 1, eCommandCat::Switch,             { {eOpParamTypes::Unk_ScriptVariable}, } },
        { "SwitchDirection",                        1, eCommandCat::Switch,         },
        { "SwitchDirectionLives",                   1, eCommandCat::Switch,         },
        { "SwitchDirectionLives2",                  1, eCommandCat::Switch,         },
        { "SwitchDirectionMark",                    4, eCommandCat::Switch,         },
        { "SwitchDungeonMode",                      1, eCommandCat::Switch,         },
        { "SwitchLives",                            1, eCommandCat::Switch,         },
        { "SwitchRandom",                           1, eCommandCat::Switch,         },
        { "SwitchScenario",                         1, eCommandCat::Switch,             { {eOpParamTypes::Unk_ScriptVariable}, } },
        { "SwitchScenarioLevel",                    1, eCommandCat::Switch,             { {eOpParamTypes::Unk_ScriptVariable}, } },
        { "SwitchSector",                           0, eCommandCat::Switch,         },
        { "SwitchValue",                            3, eCommandCat::Switch,         },
        { "SwitchVariable",                         3, eCommandCat::Switch,         },
        { "Turn2Direction",                         3, eCommandCat::SingleOp        },
        { "Turn2DirectionLives",                    3, eCommandCat::SingleOp        },
        { "Turn2DirectionLives2",                   3, eCommandCat::SingleOp        },
        { "Turn2DirectionMark",                     8, eCommandCat::SingleOp        },
        { "Turn2DirectionTurn",                     3, eCommandCat::SingleOp        },
        { "TurnDirection",                          1, eCommandCat::SingleOp        },
        { "TurnDirectionLives",                     2, eCommandCat::SingleOp        },
        { "TurnDirectionLives2",                    2, eCommandCat::SingleOp        },
        { "TurnDirectionMark",                      5, eCommandCat::SingleOp        },
        { "Unlock",                                 1, eCommandCat::Unlock          },
        { "Wait",                                   1, eCommandCat::SingleOp,       { {eOpParamTypes::Duration}, } },
        { "WaitAnimation",                          0, eCommandCat::SingleOp        },
        { "WaitBackEffect",                         0, eCommandCat::SingleOp        },
        { "WaitBack2Effect",                        0, eCommandCat::SingleOp        },
        { "WaitBgm",                                1, eCommandCat::SingleOp        },
        { "WaitBgm2",                               1, eCommandCat::SingleOp        },
        { "WaitBgmSignal",                          0, eCommandCat::SingleOp        },
        { "WaitEffect",                             0, eCommandCat::SingleOp        },
        { "WaitExecuteLives",                       1, eCommandCat::SingleOp        },
        { "WaitExecuteObject",                      1, eCommandCat::SingleOp        },
        { "WaitExecutePerformer",                   1, eCommandCat::SingleOp        },
        { "WaitFadeIn",                             0, eCommandCat::SingleOp        },
        { "WaitLockLives",                          2, eCommandCat::SingleOp        },
        { "WaitLockObject",                         2, eCommandCat::SingleOp        },
        { "WaitLockPerformer",                      2, eCommandCat::SingleOp        },
        { "WaitLockSupervision",                    1, eCommandCat::SingleOp        },
        { "WaitMe",                                 1, eCommandCat::SingleOp        },
        { "WaitMoveCamera",                         0, eCommandCat::SingleOp        },
        { "WaitMoveCamera2",                        0, eCommandCat::SingleOp        },
        { "WaitRandom",                             2, eCommandCat::SingleOp        },
        { "WaitScreenFade",                         0, eCommandCat::SingleOp        },
        { "WaitScreenFadeAll",                      0, eCommandCat::SingleOp        },
        { "WaitScreen2Fade",                        0, eCommandCat::SingleOp        },
        { "WaitSe",                                 1, eCommandCat::SingleOp        },
        { "WaitSpecialActing",                      0, eCommandCat::SingleOp        },
        { "WaitSubScreen",                          0, eCommandCat::SingleOp        },
        { "WaitSubSpecialActing",                   0, eCommandCat::SingleOp        },
        { "worldmap_BlinkMark",                     1, eCommandCat::SingleOp        },
        { "worldmap_ChangeLevel",                   1, eCommandCat::SingleOp        },
        { "worldmap_DeleteArrow",                   0, eCommandCat::SingleOp        },
        { "worldmap_MoveCamera",                    1, eCommandCat::SingleOp        },
        { "worldmap_OffMessage",                    0, eCommandCat::SingleOp        },
        { "worldmap_SetArrow",                      1, eCommandCat::SingleOp        },
        { "worldmap_SetCamera",                     1, eCommandCat::SingleOp        },
        { "worldmap_SetLevel",                      1, eCommandCat::SingleOp        },
        { "worldmap_SetMark",                       1, eCommandCat::SingleOp        },
        { "worldmap_SetMessage",                    1, eCommandCat::SingleOp        },
        { "worldmap_SetMessagePlace",               1, eCommandCat::SingleOp        },
        { "worldmap_SetMode",                       1, eCommandCat::SingleOp        },

    } };

//==============================================================================
//  OpCodesInfoListEoS
//==============================================================================
    const array<OpCodeInfoEoS, static_cast<uint16_t>(eScriptOpCodesEoS::NBOpcodes)> OpCodesInfoListEoS
    { {
//      { Opname,                   nbparams,  unk1, unk2, unk3 }
        { "Null",                                   0, -1, 0, 0, eCommandCat::Null          },
        { "back_ChangeGround",                      1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetBackEffect",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetBackScrollOffset",               2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetBackScrollSpeed",                2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetBanner",                         2,  1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetBanner2",                        6,  5, 0, 0, eCommandCat::SingleOp      },
        { "back_SetEffect",                         2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetDungeonBanner",                  2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetGround",                         1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetSpecialEpisodeBanner",           2,  1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetSpecialEpisodeBanner2",          2,  1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetSpecialEpisodeBanner3",          2,  1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetTitleBanner",                    2,  1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetWeather",                        1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetWeatherEffect",                  1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetWeatherScrollOffset",            2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back_SetWeatherScrollSpeed",             2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetBackEffect",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetBackScrollOffset",              2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetBackScrollSpeed",               2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetData",                          2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetEffect",                        2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetGround",                        1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetMode",                          1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetSpecialActing",                 3, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetWeather",                       1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetWeatherEffect",                 1, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetWeatherScrollOffset",           2, -1, 0, 0, eCommandCat::SingleOp      },
        { "back2_SetWeatherScrollSpeed",            2, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm_FadeOut",                            1, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm_Play",                               1, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm_PlayFadeIn",                         3, -1, 0, 0, eCommandCat::SingleOp,      { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::Duration}, {eOpParamTypes::UNK_Placeholder} } },
        { "bgm_Stop",                               0, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm_ChangeVolume",                       2, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm2_FadeOut",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm2_Play",                              1, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm2_PlayFadeIn",                        3, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm2_Stop",                              0, -1, 0, 0, eCommandCat::SingleOp      },
        { "bgm2_ChangeVolume",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "Branch",                                 3, -1, 1, 0, eCommandCat::BranchCmd,     { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::InstructionOffset} } },
        { "BranchBit",                              3, -1, 1, 0, eCommandCat::BranchCmd,     { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::InstructionOffset} } },
        { "BranchDebug",                            2, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchEdit",                             2, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchExecuteSub",                       2, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchPerformance",                      3, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchScenarioNow",                      4, -1, 1, 0, eCommandCat::BranchCmd,     { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::InstructionOffset} } },
        { "BranchScenarioNowAfter",                 4, -1, 1, 0, eCommandCat::BranchCmd,     { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::InstructionOffset} } },
        { "BranchScenarioNowBefore",                4, -1, 1, 0, eCommandCat::BranchCmd,     { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::InstructionOffset} } },
        { "BranchScenarioAfter",                    4, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchScenarioBefore",                   4, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchSum",                              4, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchValue",                            4, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchVariable",                         4, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "BranchVariation",                        2, -1, 1, 0, eCommandCat::BranchCmd,    },
        { "Call",                                   1, -1, 1, 0, eCommandCat::Call          },
        { "CallCommon",                             1, -1, 0, 0, eCommandCat::CallCommon    },
        { "camera_Move2Default",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move2MyPosition",                 1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move2Myself",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move2PositionMark",              -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move2PositionMark",               5, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move3Default",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move3MyPosition",                 1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move3Myself",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move3PositionMark",              -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_Move3PositionMark",               5, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_MoveDefault",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_MoveMyPosition",                  1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_MoveMyself",                      1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_MovePositionMark",               -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_MovePositionMark",                5, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_SetDefault",                      0, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_SetEffect",                       3, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_SetMyPosition",                   0, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera_SetMyself",                       0, -1, 0, 0, eCommandCat::EntAttribute  },
        { "camera_SetPositionMark",                 4, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move2Default",                   1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move2MyPosition",                1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move2Myself",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move2PositionMark",             -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move2PositionMark",              5, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move3Default",                   1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move3MyPosition",                1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move3Myself",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move3PositionMark",             -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_Move3PositionMark",              5, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_MoveDefault",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_MoveMyPosition",                 1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_MoveMyself",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_MovePositionMark",              -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_MovePositionMark",               5, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_SetDefault",                     0, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_SetEffect",                      3, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_SetMyPosition",                  0, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_SetMyself",                      0, -1, 0, 0, eCommandCat::SingleOp      },
        { "camera2_SetPositionMark",                4, -1, 0, 0, eCommandCat::SingleOp      },
        { "CancelCut",                              0, -1, 1, 0, eCommandCat::SingleOp      },
        { "CancelRecoverCommon",                    1, -1, 1, 0, eCommandCat::SingleOp      },
        { "Case",                                   2, -1, 1, 0, eCommandCat::Case,             { {eOpParamTypes::Integer},         {eOpParamTypes::CaseJumpOffset} } },
        { "CaseMenu",                               2,  0, 1, 0, eCommandCat::Case,             { {eOpParamTypes::String},          {eOpParamTypes::CaseJumpOffset} } },
        { "CaseMenu2",                              2, -1, 1, 0, eCommandCat::Case,         },
        { "CaseScenario",                           3, -1, 1, 0, eCommandCat::Case,             { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::CaseJumpOffset} } },
        { "CaseText",                               2,  1, 0, 0, eCommandCat::Case,             { {eOpParamTypes::Integer},         {eOpParamTypes::String} } },
        { "CaseValue",                              3, -1, 1, 0, eCommandCat::Case,             { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::Integer},         {eOpParamTypes::CaseJumpOffset} } }, //First could be a logical operator? Second the value to compare against, and third jump address
        { "CaseVariable",                           3, -1, 1, 0, eCommandCat::Case,         },
        { "debug_Assert",                           1, -1, 0, 0, eCommandCat::SingleOp,     },
        { "debug_Print",                            1, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Constant} } },
        { "debug_PrintFlag",                        2, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_ScriptVariable}, {eOpParamTypes::UNK_Placeholder} } },
        { "debug_PrintScenario",                    2, -1, 0, 0, eCommandCat::SingleOp,     },
        { "DefaultText",                            1,  0, 0, 0, eCommandCat::Default,          { {eOpParamTypes::String} } },
        { "Destroy",                                0, -1, 0, 0, eCommandCat::Destroy       },
        { "End",                                    0, -1, 0, 0, eCommandCat::End           },
        { "EndAnimation",                           0, -1, 0, 0, eCommandCat::SingleOp      },
        { "ExecuteActing",                          1, -1, 0, 0, eCommandCat::SingleOp      },
        { "ExecuteCommon",                          2, -1, 0, 0, eCommandCat::EntAttribute  },
        { "flag_CalcBit",                           3, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_ScriptVariable}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder} } },
        { "flag_CalcValue",                         3, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_CalcVariable",                      3, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_Clear",                             1, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_ScriptVariable} } },
        { "flag_Initial",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_Set",                               2, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_ScriptVariable}, {eOpParamTypes::Integer} } },
        { "flag_ResetDungeonResult",                0, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_ResetScenario",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_SetAdventureLog",                   1, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_SetDungeonMode",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_SetDungeonResult",                  2, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_SetPerformance",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "flag_SetScenario",                       3, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_ScriptVariable}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder} } },
        { "Flash",                                  0, -1, 0, 0, eCommandCat::SingleOp      },
        { "Hold",                                   0, -1, 0, 0, eCommandCat::Hold          },
        { "item_GetVariable",                       2, -1, 0, 0, eCommandCat::SingleOp      },
        { "item_Set",                               3, -1, 0, 0, eCommandCat::SingleOp      },
        { "item_SetTableData",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "item_SetVariable",                       2, -1, 0, 0, eCommandCat::SingleOp      },
        { "Jump",                                   1, -1, 1, 0, eCommandCat::Jump,             { {eOpParamTypes::InstructionOffset}, } },
        { "JumpCommon",                             1, -1, 0, 0, eCommandCat::JumpCommon    },
        { "lives",                                  1, -1, 0, 0, eCommandCat::EntityAccessor,   { {eOpParamTypes::Unk_LivesRef}, } },
        { "LoadPosition",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Lock",                                   1, -1, 0, 0, eCommandCat::Lock          },
        { "main_EnterAdventure",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "main_EnterDungeon",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "main_EnterGround",                       2, -1, 0, 0, eCommandCat::SingleOp      },
        { "main_EnterGroundMulti",                  3, -1, 0, 0, eCommandCat::SingleOp      },
        { "main_EnterRescueUser",                   1, -1, 0, 0, eCommandCat::SingleOp      },
        { "main_EnterTraining",                     2, -1, 0, 0, eCommandCat::SingleOp      },
        { "main_EnterTraining2",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "main_SetGround",                         1, -1, 0, 0, eCommandCat::SingleOp      },
        { "me_Play",                                1, -1, 0, 0, eCommandCat::SingleOp      },
        { "me_Stop",                                0, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_Close",                          0, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_CloseEnforce",                   0, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_Explanation",                    1,  0, 0, 0, eCommandCat::SingleOp      },
        { "message_FacePositionOffset",             2, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_ImitationSound",                 1,  0, 0, 0, eCommandCat::SingleOp      },
        { "message_KeyWait",                        0, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_Mail",                           1,  0, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::String} } },
        { "message_Menu",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_Monologue",                      1,  0, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::String} } },
        { "message_Narration",                      2,  1, 0, 0, eCommandCat::SingleOp      },
        { "message_Notice",                         1,  0, 0, 0, eCommandCat::SingleOp      },
        { "message_EmptyActor",                     0, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_ResetActor",                     0, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_SetActor",                       1, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_SetFace",                        3, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_LivesRef}, {eOpParamTypes::Unk_FaceType}, {eOpParamTypes::UNK_Placeholder} } },
        { "message_SetFaceEmpty",                   3, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_SetFaceOnly",                    3, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_SetFacePosition",                1, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_SetWaitMode",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_SpecialTalk",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "message_SwitchMenu",                     2, -1, 0, 0, eCommandCat::Switch,       },
        { "message_SwitchMenu2",                    3, -1, 0, 0, eCommandCat::Switch,       },
        { "message_SwitchMonologue",                1, -1, 0, 0, eCommandCat::Switch,           { {eOpParamTypes::Unk_ScriptVariable} } },
        { "message_SwitchTalk",                     1, -1, 0, 0, eCommandCat::Switch,           { {eOpParamTypes::Unk_ScriptVariable} } },
        { "message_Talk",                           1,  0, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::String} } },
        { "Move2Position",                          3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move2PositionLives",                     2, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move2PositionMark",                     -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move2PositionMark",                      5, -1, 0, 0, eCommandCat::EntAttribute  },
        { "Move2PositionOffset",                   -1, -1, 0, 0, eCommandCat::EntAttribute  },
        { "Move2PositionOffset",                    3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move2PositionOffsetRandom",              3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move3Position",                          3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move3PositionLives",                     2, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move3PositionMark",                     -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move3PositionMark",                      5, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move3PositionOffset",                   -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move3PositionOffset",                    3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Move3PositionOffsetRandom",              3, -1, 0, 0, eCommandCat::SingleOp      },
        { "MoveDirection",                          3, -1, 0, 0, eCommandCat::SingleOp      },
        { "MoveHeight",                             2, -1, 0, 0, eCommandCat::SingleOp      },
        { "MovePosition",                           3, -1, 0, 0, eCommandCat::SingleOp      },
        { "MovePositionLives",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "MovePositionLivesTime",                  3, -1, 0, 0, eCommandCat::SingleOp      },
        { "MovePositionMark",                      -1, -1, 0, 0, eCommandCat::EntAttribute  },
        { "MovePositionMark",                       5, -1, 0, 0, eCommandCat::EntAttribute  },
        { "MovePositionMarkTime",                   6, -1, 0, 0, eCommandCat::SingleOp      },
        { "MovePositionOffset",                    -1, -1, 0, 0, eCommandCat::EntAttribute  },
        { "MovePositionOffset",                     3, -1, 0, 0, eCommandCat::EntAttribute  },
        { "MoveSpecial",                            3, -1, 0, 0, eCommandCat::SingleOp      },
        { "MoveTurn",                               3, -1, 0, 0, eCommandCat::SingleOp      },
        { "object",                                 1, -1, 0, 0, eCommandCat::EntityAccessor,   { {eOpParamTypes::Unk_ObjectRef}, } },
        { "PauseEffect",                            1, -1, 0, 0, eCommandCat::SingleOp      },
        { "performer",                              1, -1, 0, 0, eCommandCat::EntityAccessor,   { {eOpParamTypes::Unk_PerformerRef} } },
        { "ProcessSpecial",                         3, -1, 0, 0, eCommandCat::ProcSpec,         { {eOpParamTypes::Unk_ProcSpec}, {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::UNK_Placeholder} } },
        { "PursueTurnLives",                        4, -1, 0, 0, eCommandCat::SingleOp      },
        { "PursueTurnLives2",                       4, -1, 0, 0, eCommandCat::SingleOp      },
        { "ResetAttribute",                         1, -1, 0, 0, eCommandCat::SingleOp      },
        { "ResetFunctionAttribute",                 1, -1, 0, 0, eCommandCat::SingleOp      },
        { "ResetHitAttribute",                      1, -1, 0, 0, eCommandCat::SingleOp      },
        { "ResetOutputAttribute",                   1, -1, 0, 0, eCommandCat::SingleOp      },
        { "ResetReplyAttribute",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "ResumeEffect",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Return",                                 0, -1, 0, 0, eCommandCat::Return        },
        { "SavePosition",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_FadeChange",                      4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_FadeChangeAll",                   4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_FadeIn",                          2, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Boolean}, {eOpParamTypes::Duration} } },
        { "screen_FadeInAll",                       2, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Boolean}, {eOpParamTypes::Duration} } },
        { "screen_FadeOut",                         2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_FadeOutAll",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_FlushChange",                     8, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_FlushIn",                         6, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_FlushOut",                        6, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_WhiteChange",                     4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_WhiteChangeAll",                  4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_WhiteIn",                         2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_WhiteInAll",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_WhiteOut",                        2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen_WhiteOutAll",                     2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FadeChange",                     4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FadeChangeAll",                  4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FadeIn",                         2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FadeInAll",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FadeOut",                        2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FadeOutAll",                     2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FlushChange",                    8, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FlushIn",                        6, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_FlushOut",                       6, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_WhiteChange",                    4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_WhiteChangeAll",                 4, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_WhiteIn",                        2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_WhiteInAll",                     2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_WhiteOut",                       2, -1, 0, 0, eCommandCat::SingleOp      },
        { "screen2_WhiteOutAll",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_ChangePan",                           3, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_ChangeVolume",                        3, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_FadeOut",                             2, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_Play",                                1, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_PlayFull",                            3, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_PlayPan",                             2, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_PlayVolume",                          2, -1, 0, 0, eCommandCat::SingleOp      },
        { "se_Stop",                                1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetAnimation",                           1, -1, 0, 0, eCommandCat::EntAttribute,      { {eOpParamTypes::Integer}, } },
        { "SetAttribute",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetBlink",                               2, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetDirection",                           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetDirectionLives",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetEffect",                              2, -1, 0, 0, eCommandCat::EntAttribute  },
        { "SetFunctionAttribute",                   1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetHeight",                              1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetHitAttribute",                        1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetMoveRange",                           6, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetOutputAttribute",                     1, -1, 0, 0, eCommandCat::EntAttribute  },
        { "SetPosition",                            2, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetPositionInitial",                     0, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetPositionLives",                       1, -1, 0, 0, eCommandCat::EntAttribute  },
        { "SetPositionMark",                        4, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetPositionOffset",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetPositionOffsetRandom",                2, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetReplyAttribute",                      1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SetupOutputAttributeAndAnimation",       3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide2Position",                         3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide2PositionLives",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide2PositionMark",                    -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide2PositionMark",                     5, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide2PositionOffset",                  -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide2PositionOffset",                   3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide2PositionOffsetRandom",             3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide3Position",                         3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide3PositionLives",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide3PositionMark",                    -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide3PositionMark",                     5, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide3PositionOffset",                  -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide3PositionOffset",                   3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Slide3PositionOffsetRandom",             3, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlideHeight",                            2, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlidePosition",                          3, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlidePositionLives",                     2, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlidePositionLivesTime",                 3, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlidePositionMark",                     -1, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlidePositionMark",                      5, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlidePositionMarkTime",                  6, -1, 0, 0, eCommandCat::SingleOp      },
        { "SlidePositionOffset",                   -1, -1, 0, 0, eCommandCat::EntAttribute  },
        { "SlidePositionOffset",                    3, -1, 0, 0, eCommandCat::EntAttribute  },
        { "sound_FadeOut",                          1, -1, 0, 0, eCommandCat::SingleOp      },
        { "sound_Stop",                             0, -1, 0, 0, eCommandCat::SingleOp      },
        { "StopAnimation",                          0, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_Acting",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ActingInvisible",            1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteActing",              3, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteActingSub",           3, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::Constant}, {eOpParamTypes::UNK_Placeholder} } },
        { "supervision_ExecuteCommon",              1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteEnter",               1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteStation",             3, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteStationCommon",       2, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteStationCommonSub",    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteStationSub",          3, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::UNK_Placeholder}, {eOpParamTypes::Constant}, {eOpParamTypes::UNK_Placeholder} } },
        { "supervision_ExecuteExport",              1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_ExecuteExportSub",           1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_LoadStation",                2, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_Remove",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_RemoveActing",               1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_RemoveCommon",               1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_SpecialActing",              3, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_Station",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_StationCommon",              1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision_Suspend",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "supervision2_SpecialActing",             3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Switch",                                 1, -1, 0, 0, eCommandCat::Switch,           { {eOpParamTypes::Unk_ScriptVariable}, } },
        { "SwitchDirection",                        1, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchDirectionLives",                   1, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchDirectionLives2",                  1, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchDirectionMark",                    4, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchDungeonMode",                      1, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchLives",                            1, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchRandom",                           1, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchScenario",                         1, -1, 0, 0, eCommandCat::Switch,           { {eOpParamTypes::Unk_ScriptVariable}, } },
        { "SwitchScenarioLevel",                    1, -1, 0, 0, eCommandCat::Switch,           { {eOpParamTypes::Unk_ScriptVariable}, } },
        { "SwitchSector",                           0, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchValue",                            3, -1, 0, 0, eCommandCat::Switch        },
        { "SwitchVariable",                         3, -1, 0, 0, eCommandCat::Switch        },
        { "Turn2Direction",                         3, -1, 0, 0, eCommandCat::EntAttribute  },
        { "Turn2DirectionLives",                    3, -1, 0, 0, eCommandCat::EntAttribute  },
        { "Turn2DirectionLives2",                   3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Turn2DirectionMark",                     8, -1, 0, 0, eCommandCat::EntAttribute  },
        { "Turn2DirectionTurn",                     3, -1, 0, 0, eCommandCat::SingleOp      },
        { "Turn3",                                  4, -1, 0, 0, eCommandCat::SingleOp      },
        { "TurnDirection",                          1, -1, 0, 0, eCommandCat::SingleOp      },
        { "TurnDirectionLives",                     2, -1, 0, 0, eCommandCat::EntAttribute  },
        { "TurnDirectionLives2",                    2, -1, 0, 0, eCommandCat::SingleOp      },
        { "TurnDirectionMark",                      5, -1, 0, 0, eCommandCat::SingleOp      },
        { "Unlock",                                 1, -1, 0, 0, eCommandCat::Unlock        },
        { "Wait",                                   1, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Duration}, } },
        { "WaitAnimation",                          0, -1, 0, 0, eCommandCat::EntAttribute  },
        { "WaitBackEffect",                         0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitBack2Effec",                         0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitBgm",                                1, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitBgm2",                               1, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitBgmSignal",                          0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitEffect",                             0, -1, 0, 0, eCommandCat::EntAttribute  },
        { "WaitEndAnimation",                       0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitExecuteLives",                       1, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_LivesRef} } },
        { "WaitExecuteObject",                      1, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_ObjectRef} } },
        { "WaitExecutePerformer",                   1, -1, 0, 0, eCommandCat::SingleOp,         { {eOpParamTypes::Unk_PerformerRef} } },
        { "WaitFadeIn",                             0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitLockLives",                          2, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitLockObject",                         2, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitLockPerformer",                      2, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitLockSupervision",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitMe",                                 1, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitMoveCamera",                         0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitMoveCamera2",                        0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitRandom",                             2, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitScreenFade",                         0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitScreenFadeAll",                      0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitScreen2Fade",                        0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitSe",                                 1, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitSpecialActing",                      0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitSubScreen",                          0, -1, 0, 0, eCommandCat::SingleOp      },
        { "WaitSubSpecialActing",                   0, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_BlinkMark",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_ChangeLevel",                   1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_DeleteArrow",                   0, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_MoveCamera",                    1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_OffMessage",                    0, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_SetArrow",                      1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_SetCamera",                     1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_SetLevel",                      1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_SetMark",                       1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_SetMessage",                    1,  0, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_SetMessagePlace",               1, -1, 0, 0, eCommandCat::SingleOp      },
        { "worldmap_SetMode",                       1, -1, 0, 0, eCommandCat::SingleOp      },
    } };

//
//
//


    const std::array<gamevariableinfo, 115> GameVariableInfoTbl
    {{
        { 8,    0x2,    0x0,    0x0,    0x1,    0x1, "VERSION"},
        { 8,    0x2,    0x4,    0x0,    0x1,    0x0, "CONDITION"},
        { 3,    0x6,   0xBA,    0x0,    0x2,    0x0, "SCENARIO_SELECT"},
        { 3,    0x6,   0xBC,    0x0,    0x2,    0x0, "SCENARIO_MAIN"},
        { 3,    0x6,   0xBE,    0x0,    0x2,    0x0, "SCENARIO_SIDE"},
        { 3,    0x6,   0xC0,    0x0,    0x2,    0x0, "SCENARIO_SUB1"},
        { 3,    0x6,   0xC2,    0x0,    0x2,    0x0, "SCENARIO_SUB2"},
        { 3,    0x6,   0xC4,    0x0,    0x2,    0x0, "SCENARIO_SUB3"},
        { 3,    0x6,   0xC6,    0x0,    0x2,    0x0, "SCENARIO_SUB4"},
        { 3,    0x6,   0xC8,    0x0,    0x2,    0x0, "SCENARIO_SUB5"},
        { 3,    0x6,   0xCA,    0x0,    0x2,    0x0, "SCENARIO_SUB6"},
        { 3,    0x6,   0xCC,    0x0,    0x2,    0x0, "SCENARIO_SUB7"},
        { 3,    0x6,   0xCE,    0x0,    0x2,    0x0, "SCENARIO_SUB8"},
        { 1,    0x6,  0x11B,    0x0,    0x3,    0x0, "SIDE02_TALK"},
        { 1,    0x6,  0x11B,    0x3,    0x3,    0x0, "SIDE06_ROOM"},
        { 1,    0x6,  0x11B,    0x6,    0x1,    0x0, "SIDE08_BOSS2ND"},
        { 1,    0x6,  0x11B,    0x7,    0x1,    0x0, "SIDE01_BOSS2ND"},
        { 1,    0x6,  0x11C,    0x0,   0x80,    0x0, "SCENARIO_MAIN_BIT_FLAG"},
        { 1,    0x6,  0x12C,    0x0,  0x100,    0x0, "SCENARIO_TALK_BIT_FLAG"},
        { 4,    0x6,   0xB0,    0x0,    0x1,    0x0, "SCENARIO_BALANCE_FLAG"},
        { 4,    0x6,   0xB1,    0x0,    0x1,    0x0, "SCENARIO_BALANCE_DEBUG"},
        { 3,    0x6,   0xD0,    0x0,    0x1,    0x0, "CRYSTAL_COLOR_01"},
        { 3,    0x6,   0xD1,    0x0,    0x1,    0x0, "CRYSTAL_COLOR_02"},
        { 3,    0x6,   0xD2,    0x0,    0x1,    0x0, "CRYSTAL_COLOR_03"},
        { 3,    0x6,   0xD3,    0x0,    0x1,    0x0, "COMPULSORY_SAVE_POINT"},
        { 3,    0x6,   0xD4,    0x0,    0x1,    0x0, "COMPULSORY_SAVE_POINT_SIDE"},
        { 3,    0x6,   0xD5,    0x0,    0x8,    0x0, "SCENARIO_SELECT_BACKUP"},
        { 1,    0x6,  0x14C,    0x0,  0x200,    0x0, "SCENARIO_MAIN_BIT_FLAG_BACKUP"},
        { 6,    0x2,   0x30,    0x0,    0x1,    0x0, "GROUND_ENTER"},
        { 3,    0x2,   0xDD,    0x0,    0x1,    0x0, "GROUND_ENTER_LINK"},
        { 6,    0x2,   0x32,    0x0,    0x1,    0x0, "GROUND_GETOUT"},
        { 6,    0x2,   0x34,    0x0,    0x1,    0x0, "GROUND_MAP"},
        { 6,    0x2,   0x36,    0x0,    0x1,    0x0, "GROUND_PLACE"},
        { 6,    0x2,   0x38,    0x0,    0x5,    0x0, "GROUND_ENTER_BACKUP"},
        { 3,    0x2,   0xDE,    0x0,    0x5,    0x0, "GROUND_ENTER_LINK_BACKUP"},
        { 6,    0x2,   0x42,    0x0,    0x5,    0x0, "GROUND_GETOUT_BACKUP"},
        { 6,    0x2,   0x4C,    0x0,    0x5,    0x0, "GROUND_MAP_BACKUP"},
        { 6,    0x2,   0x56,    0x0,    0x5,    0x0, "GROUND_PLACE_BACKUP"},
        { 6,    0x2,   0x60,    0x0,    0x1,    0x0, "DUNGEON_SELECT"},
        { 6,    0x2,   0x62,    0x0,    0x1,    0x0, "DUNGEON_ENTER"},
        { 6,    0x2,   0x64,    0x0,    0x1,    0x0, "DUNGEON_ENTER_MODE"},
        { 6,    0x2,   0x66,    0x0,    0x1,    0x0, "DUNGEON_ENTER_INDEX"},
        { 5,    0x2,   0xA4,    0x0,    0x1,    0x0, "DUNGEON_ENTER_FREQUENCY"},
        { 3,    0x2,   0xE3,    0x0,    0x1,    0x0, "DUNGEON_RESULT"},
        { 3,    0x2,   0xE4,    0x0,    0x1,    0x0, "GROUND_START_MODE"},
        { 6,    0x2,   0x68,    0x0,    0x5,    0x0, "DUNGEON_ENTER_BACKUP"},
        { 6,    0x2,   0x72,    0x0,    0x5,    0x0, "DUNGEON_ENTER_MODE_BACKUP"},
        { 6,    0x2,   0x7C,    0x0,    0x5,    0x0, "DUNGEON_ENTER_INDEX_BACKUP"},
        { 5,    0x2,   0xA6,    0x0,    0x5,    0x0, "DUNGEON_ENTER_FREQUENCY_BACKUP"},
        { 3,    0x2,   0xE5,    0x0,    0x5,    0x0, "DUNGEON_RESULT_BACKUP"},
        { 3,    0x2,   0xEA,    0x0,    0x5,    0x0, "GROUND_START_MODE_BACKUP"},
        { 3,    0x2,   0xEF,    0x0,    0x1,    0x0, "REQUEST_CLEAR_COUNT"},
        { 3,    0x2,   0xF0,    0x0,    0x1,    0x0, "PLAYER_KIND"},
        { 3,    0x2,   0xF1,    0x0,    0x1,    0x0, "ATTENDANT1_KIND"},
        { 3,    0x2,   0xF2,    0x0,    0x1,    0x0, "ATTENDANT2_KIND"},
        { 3,    0x2,   0xF3,    0x0,    0x5,    0x0, "PLAYER_KIND_BACKUP"},
        { 3,    0x2,   0xF8,    0x0,    0x5,    0x0, "ATTENDANT1_KIND_BACKUP"},
        { 3,    0x2,   0xFD,    0x0,    0x5,    0x0, "ATTENDANT2_KIND_BACKUP"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "FRIEND_SUM"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "UNIT_SUM"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "CARRY_GOLD"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "BANK_GOLD"},
        { 6,    0x2,   0x86,    0x0,    0x1,    0x0, "HERO_FIRST_KIND"},
        { 2,    0x2,  0x107,    0x0,    0xA,    0x0, "HERO_FIRST_NAME"},
        { 6,    0x2,   0x88,    0x0,    0x1,    0x0, "PARTNER_FIRST_KIND"},
        { 2,    0x2,  0x111,    0x0,    0xA,    0x0, "PARTNER_FIRST_NAME"},
        { 4,    0x2,   0xB2,    0x0,    0x1,    0x0, "HERO_TALK_KIND"},
        { 4,    0x2,   0xB3,    0x0,    0x1,    0x0, "PARTNER_TALK_KIND"},
        { 6,    0x2,   0x8A,    0x0,    0x1,    0x0, "RANDOM_REQUEST_NPC03_KIND"},
        { 4,    0x2,   0xB4,    0x0,    0x1,    0x0, "CONFIG_COLOR_KIND"},
        { 4,    0x2,   0xB5,    0x0,    0x1,    0x0, "ROM_VARIATION"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "LANGUAGE_TYPE"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "GAME_MODE"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "EXECUTE_SPECIAL_EPISODE_TYPE"},
        { 4,    0x2,   0xB6,    0x0,    0x1,    0x0, "SPECIAL_EPISODE_TYPE"},
        { 1,    0x2,  0x18C,    0x0,    0x8,    0x0, "SPECIAL_EPISODE_OPEN"},
        { 1,    0x2,  0x18D,    0x0,    0x8,    0x0, "SPECIAL_EPISODE_OPEN_OLD"},
        { 1,    0x2,  0x18E,    0x0,    0x8,    0x0, "SPECIAL_EPISODE_CONQUEST"},
        { 1,    0x2,  0x18F,    0x0,   0x40,    0x0, "PERFORMANCE_PROGRESS_LIST"},
        { 1,    0x4,  0x197,    0x0,  0x100,    0x0, "DUNGEON_OPEN_LIST"},
        { 1,    0x4,  0x1B7,    0x0,  0x100,    0x0, "DUNGEON_ENTER_LIST"},
        { 1,    0x4,  0x1D7,    0x0,  0x100,    0x0, "DUNGEON_ARRIVE_LIST"},
        { 1,    0x4,  0x1F7,    0x0,  0x100,    0x0, "DUNGEON_CONQUEST_LIST"},
        { 1,    0x4,  0x217,    0x0,  0x100,    0x0, "DUNGEON_PRESENT_LIST"},
        { 1,    0x4,  0x237,    0x0,  0x100,    0x0, "DUNGEON_REQUEST_LIST"},
        { 1,    0x5,  0x257,    0x0,  0x140,    0x0, "WORLD_MAP_MARK_LIST_NORMAL"},
        { 1,    0x5,  0x27F,    0x0,  0x140,    0x0, "WORLD_MAP_MARK_LIST_SPECIAL"},
        { 3,    0x5,  0x102,    0x0,    0x1,    0x0, "WORLD_MAP_LEVEL"},
        { 7,    0x2,    0x8,    0x0,    0x3,    0x0, "POSITION_X"},
        { 7,    0x2,   0x14,    0x0,    0x3,    0x0, "POSITION_Y"},
        { 7,    0x2,   0x20,    0x0,    0x3,    0x0, "POSITION_HEIGHT"},
        { 4,    0x2,   0xB7,    0x0,    0x3,    0x0, "POSITION_DIRECTION"},
        { 6,    0x5,   0x8C,    0x0,    0x1,    0x0, "EVENT_LOCAL"},
        { 6,    0x4,   0x8E,    0x0,    0x1,    0x0, "DUNGEON_EVENT_LOCAL"},
        { 1,    0x5,  0x2A7,    0x0,   0x20,    0x0, "STATION_ITEM_STATIC"},
        { 1,    0x5,  0x2AB,    0x0,   0x20,    0x0, "STATION_ITEM_TEMP"},
        { 1,    0x5,  0x2AF,    0x0,   0x10,    0x0, "DELIVER_ITEM_STATIC"},
        { 1,    0x5,  0x2B1,    0x0,   0x10,    0x0, "DELIVER_ITEM_TEMP"},
        { 1,    0x6,  0x2B3,    0x0,    0x5,    0x0, "BIT_FUWARANTE_LOCAL"},
        { 3,    0x6,  0x103,    0x0,    0x1,    0x0, "LOTTERY_RESULT"},
        { 6,    0x2,   0x90,    0x0,    0x2,    0x0, "ITEM_BACKUP"},
        { 6,    0x2,   0x94,    0x0,    0x2,    0x0, "ITEM_BACKUP_KUREKURE"},
        { 6,    0x2,   0x98,    0x0,    0x2,    0x0, "ITEM_BACKUP_TAKE"},
        { 6,    0x2,   0x9C,    0x0,    0x2,    0x0, "ITEM_BACKUP_GET"},
        { 6,    0x2,   0xA0,    0x0,    0x1,    0x0, "REQUEST_THANKS_RESULT_KIND"},
        { 6,    0x2,   0xA2,    0x0,    0x1,    0x0, "REQUEST_THANKS_RESULT_VARIATION"},
        { 1,    0x6,  0x2B3,    0x5,    0x1,    0x0, "SUB30_TREASURE_DISCOVER"},
        { 1,    0x6,  0x2B3,    0x6,    0x1,    0x0, "SUB30_SPOT_DISCOVER"},
        { 7,    0x2,   0x2C,    0x0,    0x1,    0x0, "RECYCLE_COUNT"},
        { 3,    0x2,  0x104,    0x0,    0x1,    0x0, "SUB30_SPOT_LEVEL"},
        { 3,    0x2,  0x105,    0x0,    0x1,    0x0, "TEAM_RANK_EVENT_LEVEL"},
        { 3,    0x2,  0x106,    0x0,    0x1,    0x0, "PLAY_OLD_GAME"},
        { 9,    0x2,    0x0,    0x0,    0x1,    0x0, "NOTE_MODIFY_FLAG"},
        { 1,    0x6,  0x2B3,    0x7,    0x1,    0x0, "SUB30_PROJECTP"},
        { 0,    0x0,  0x2B4,    0x0,    0x0,    0x0, "SUM" },
    }};

    const std::array<gamevariableinfo, 4> GameVariableInfoTblEx
    {{
        {6,    0x7,    0x0,    0x0,    0x1,    0x0, "LOCAL0"},
        {6,    0x7,    0x2,    0x0,    0x1,    0x0, "LOCAL1"},
        {6,    0x7,    0x2,    0x0,    0x1,    0x0, "LOCAL2"},
        {6,    0x7,    0x2,    0x0,    0x1,    0x0, "LOCAL3"},
    }};

    const gamevariableinfo * FindGameVarInfo( uint16_t varid )
    {
        if((varid & 0x400u) > 0 && (varid - 0x400u) < GameVariableInfoTblEx.size())
            return &(GameVariableInfoTblEx[(varid - 0x400u)]);
        else if( varid < GameVariableInfoTbl.size() )
            return &(GameVariableInfoTbl[varid]);
        else
            return nullptr;
    }

    uint16_t GameVarInfoNameToId( const std::string & name )
    {
        for( size_t i = 0; i < GameVariableInfoTbl.size(); ++i )
        {
            const gamevariableinfo & cur = GameVariableInfoTbl[i];
            if( cur.str == name )
                return static_cast<uint16_t>(i);
        }
        //Check the second table
        for( size_t i = 0; i < GameVariableInfoTblEx.size(); ++i )
        {
            const gamevariableinfo & cur = GameVariableInfoTblEx[i];
            if( cur.str == name )
                return static_cast<uint16_t>(i);
        }
        return std::numeric_limits<uint16_t>::max();
    }


//
//
//

    bool IsOpCodeData(uint16_t code, eGameVersion vers)
    {
        if( vers == eGameVersion::EoS )
        {
            if( code > (OpCodeNumberPicker<eOpCodeVersion::EoS>()()) )
                return true;
        }
        else if( vers == eGameVersion::EoT || vers == eGameVersion::EoD )
        {
            if( code > (OpCodeNumberPicker<eOpCodeVersion::EoTD>()()) )
                return true;
        }
        else
            throw std::runtime_error("IsOpCodeData(): Invalid game version specified!");
        return false;
    }

};