#include "pmd2_scripts_opcodes.hpp"

namespace pmd2
{

//==============================================================================
//  OpCodesInfoListEoTD
//==============================================================================
    const std::vector<OpCodeInfoEoTD> OpCodesInfoListEoTD =
    { {
//      { Opname,                            nbparams,  unk1, unk2, unk3 }
        { "null",                                   0 },
        { "back_ChangeGround",                      1 },
        { "back_SetBackEffect",                     1 },
        { "back_SetBackScrollOffset",               2 },
        { "back_SetBackScrollSpeed",                2 },
        { "back_SetBanner",                         2 },
        { "back_SetEffect",                         2 },
        { "back_SetDungeonBanner",                  2 },
        { "back_SetGround",                         1 },
        { "back_SetTitleBanner",                    2 },
        { "back_SetWeather",                        1 },
        { "back_SetWeatherEffect",                  1 },
        { "back_SetWeatherScrollOffset",            2 },
        { "back_SetWeatherScrollSpeed",             2 },
        { "back2_SetBackEffect",                    1 },
        { "back2_SetBackScrollOffset",              2 },
        { "back2_SetBackScrollSpeed",               2 },
        { "back2_SetData",                          2 },
        { "back2_SetEffect",                        2 },
        { "back2_SetGround",                        1 },
        { "back2_SetMode",                          1 },
        { "back2_SetSpecialActing",                 3 },
        { "back2_SetWeather",                       1 },
        { "back2_SetWeatherEffect",                 1 },
        { "back2_SetWeatherScrollOffset",           2 },
        { "back2_SetWeatherScrollSpeed",            2 },
        { "bgm_FadeOut",                            1 },
        { "bgm_Play",                               1 },
        { "bgm_PlayFadeIn",                         3 },
        { "bgm_Stop",                               0 },
        { "bgm_ChangeVolume",                       2 },
        { "bgm2_FadeOut",                           1 },
        { "bgm2_Play",                              1 },
        { "bgm2_PlayFadeIn",                        3 },
        { "bgm2_Stop",                              0 },
        { "bgm2_ChangeVolume",                      2 },
        { "Branch",                                 3 },
        { "BranchBit",                              3 },
        { "BranchDebug",                            2 },
        { "BranchEdit",                             2 },
        { "BranchExecuteSub",                       2 },
        { "BranchPerformance",                      3 },
        { "BranchScenarioNow",                      4 },
        { "BranchScenarioNowAfter",                 4 },
        { "BranchScenarioNowBefore",                4 },
        { "BranchScenarioAfter",                    4 },
        { "BranchScenarioBefore",                   4 },
        { "BranchSum",                              4 },
        { "BranchValue",                            4 },
        { "BranchVariable",                         4 },
        { "BranchVariation",                        2 },
        { "Call",                                   1 },
        { "CallCommon",                             1 },
        { "camera_Move2Default",                    1 },
        { "camera_Move2MyPosition",                 1 },
        { "camera_Move2Myself",                     1 },
        { "camera_Move2PositionMark",               5 },
        { "camera_Move3Default",                    1 },
        { "camera_Move3MyPosition",                 1 },
        { "camera_Move3Myself",                     1 },
        { "camera_Move3PositionMark",               5 },
        { "camera_MoveDefault",                     1 },
        { "camera_MoveMyPosition",                  1 },
        { "camera_MoveMyself",                      1 },
        { "camera_MovePositionMark",                5 },
        { "camera_SetDefault",                      0 },
        { "camera_SetEffect",                       3 },
        { "camera_SetMyPosition",                   0 },
        { "camera_SetMyself",                       0 },
        { "camera_SetPositionMark",                 4 },
        { "camera2_Move2Default",                   1 },
        { "camera2_Move2MyPosition",                1 },
        { "camera2_Move2Myself",                    1 },
        { "camera2_Move2PositionMark",              5 },
        { "camera2_Move3Default",                   1 },
        { "camera2_Move3MyPosition",                1 },
        { "camera2_Move3Myself",                    1 },
        { "camera2_Move3PositionMark",              5 },
        { "camera2_MoveDefault",                    1 },
        { "camera2_MoveMyPosition",                 1 },
        { "camera2_MoveMyself",                     1 },
        { "camera2_MovePositionMark",               5 },
        { "camera2_SetDefault",                     0 },
        { "camera2_SetEffect",                      3 },
        { "camera2_SetMyPosition",                  0 },
        { "camera2_SetMyself",                      0 },
        { "camera2_SetPositionMark",                4 },
        { "Case",                                   2 },
        { "CaseMenu",                               2 },
        { "CaseScenario",                           3 },
        { "CaseText",                               2 },
        { "CaseValue",                              3 },
        { "CaseVariable",                           3 },
        { "debug_Assert",                           1 },
        { "debug_Print",                            1 },
        { "debug_PrintFlag",                        2 },
        { "debug_PrintScenario",                    2 },
        { "DefaultText",                            1 },
        { "Destroy",                                0 },
        { "End",                                    0 },
        { "ExecuteActing",                          1 },
        { "ExecuteCommon",                          2 },
        { "flag_CalcBit",                           3 },
        { "flag_CalcValue",                         3 },
        { "flag_CalcVariable",                      3 },
        { "flag_Clear",                             1 },
        { "flag_Initial",                           1 },
        { "flag_Set",                               2 },
        { "flag_ResetDungeonResult",                0 },
        { "flag_ResetScenario",                     1 },
        { "flag_SetAdventureLog",                   1 },
        { "flag_SetDungeonMode",                    2 },
        { "flag_SetDungeonResult",                  2 },
        { "flag_SetPerformance",                    2 },
        { "flag_SetScenario",                       3 },
        { "Flash",                                  0 },
        { "Hold",                                   0 },
        { "Jump",                                   1 },
        { "JumpCommon",                             1 },
        { "lives",                                  1 },
        { "LoadPosition",                           1 },
        { "Lock",                                   1 },
        { "main_EnterAdventure",                    2 },
        { "main_EnterDungeon",                      2 },
        { "main_EnterGround",                       2 },
        { "main_EnterGroundMulti",                  3 },
        { "main_EnterRescueUser",                   1 },
        { "main_EnterTraining",                     2 },
        { "main_EnterTraining2",                    2 },
        { "main_SetGround",                         1 },
        { "me_Play",                                1 },
        { "me_Stop",                                0 },
        { "message_Close",                          0 },
        { "message_CloseEnforce",                   0 },
        { "message_Explanation",                    1 },
        { "message_FacePositionOffset",             2 },
        { "message_ImitationSound",                 1 },
        { "message_KeyWait",                        0 },
        { "message_Mail",                           1 },
        { "message_Menu",                           1 },
        { "message_Monologue",                      1 },
        { "message_Narration",                      2 },
        { "message_Notice",                         1 },
        { "message_EmptyActor",                     0 },
        { "message_ResetActor",                     0 },
        { "message_SetActor",                       1 },
        { "message_SetFace",                        3 },
        { "message_SetFaceEmpty",                   3 },
        { "message_SetFaceOnly",                    3 },
        { "message_SetFacePosition",                1 },
        { "message_SetWaitMode",                    2 },
        { "message_SpecialTalk",                    1 },
        { "message_SwitchMenu",                     2 },
        { "message_SwitchMonologue",                1 },
        { "message_SwitchTalk",                     1 },
        { "message_Talk",                           1 },
        { "Move2Position",                          3 },
        { "Move2PositionLives",                     2 },
        { "Move2PositionMark",                      5 },
        { "Move2PositionOffset",                    3 },
        { "Move2PositionOffsetRandom",              3 },
        { "Move3Position",                          3 },
        { "Move3PositionLives",                     2 },
        { "Move3PositionMark",                      5 },
        { "Move3PositionOffset",                    3 },
        { "Move3PositionOffsetRandom",              3 },
        { "MoveDirection",                          3 },
        { "MoveHeight",                             2 },
        { "MovePosition",                           3 },
        { "MovePositionLives",                      2 },
        { "MovePositionLivesTime",                  3 },
        { "MovePositionMark",                       5 },
        { "MovePositionMarkTime",                   6 },
        { "MovePositionOffset",                     3 },
        { "MoveSpecial",                            3 },
        { "MoveTurn",                               3 },
        { "object",                                 1 },
        { "performer",                              1 },
        { "ProcessSpecial",                         3 },
        { "ResetAttribute",                         1 },
        { "ResetFunctionAttribute",                 1 },
        { "ResetHitAttribute",                      1 },
        { "ResetOutputAttribute",                   1 },
        { "ResetReplyAttribute",                    1 },
        { "Return",                                 0 },
        { "SavePosition",                           1 },
        { "screen_FadeChange",                      4 },
        { "screen_FadeChangeAll",                   4 },
        { "screen_FadeIn",                          2 },
        { "screen_FadeInAll",                       2 },
        { "screen_FadeOut",                         2 },
        { "screen_FadeOutAll",                      2 },
        { "screen_FlushChange",                     8 },
        { "screen_FlushIn",                         6 },
        { "screen_FlushOut",                        6 },
        { "screen_WhiteChange",                     4 },
        { "screen_WhiteChangeAll",                  4 },
        { "screen_WhiteIn",                         2 },
        { "screen_WhiteInAll",                      2 },
        { "screen_WhiteOut",                        2 },
        { "screen_WhiteOutAll",                     2 },
        { "screen2_FadeChange",                     4 },
        { "screen2_FadeChangeAll",                  4 },
        { "screen2_FadeIn",                         2 },
        { "screen2_FadeInAll",                      2 },
        { "screen2_FadeOut",                        2 },
        { "screen2_FadeOutAll",                     2 },
        { "screen2_FlushChange",                    8 },
        { "screen2_FlushIn",                        6 },
        { "screen2_FlushOut",                       6 },
        { "screen2_WhiteChange",                    4 },
        { "screen2_WhiteChangeAll",                 4 },
        { "screen2_WhiteIn",                        2 },
        { "screen2_WhiteInAll",                     2 },
        { "screen2_WhiteOut",                       2 },
        { "screen2_WhiteOutAll",                    2 },
        { "se_FadeOut",                             2 },
        { "se_Play",                                1 },
        { "se_Stop",                                1 },
        { "SetAnimation",                           1 },
        { "SetAttribute",                           1 },
        { "SetDirection",                           1 },
        { "SetDirectionLives",                      2 },
        { "SetEffect",                              2 },
        { "SetFunctionAttribute",                   1 },
        { "SetHeight",                              1 },
        { "SetHitAttribute",                        1 },
        { "SetMoveRange",                           6 },
        { "SetOutputAttribute",                     1 },
        { "SetPosition",                            2 },
        { "SetPositionInitial",                     0 },
        { "SetPositionLives",                       1 },
        { "SetPositionMark",                        4 },
        { "SetPositionOffset",                      2 },
        { "SetPositionOffsetRandom",                2 },
        { "SetReplyAttribute",                      1 },
        { "Slide2Position",                         3 },
        { "Slide2PositionLives",                    2 },
        { "Slide2PositionMark",                     5 },
        { "Slide2PositionOffset",                   3 },
        { "Slide2PositionOffsetRandom",             3 },
        { "Slide3Position",                         3 },
        { "Slide3PositionLives",                    2 },
        { "Slide3PositionMark",                     5 },
        { "Slide3PositionOffset",                   3 },
        { "Slide3PositionOffsetRandom",             3 },
        { "SlideHeight",                            2 },
        { "SlidePosition",                          3 },
        { "SlidePositionLives",                     2 },
        { "SlidePositionLivesTime",                 3 },
        { "SlidePositionMark",                      5 },
        { "SlidePositionMarkTime",                  6 },
        { "SlidePositionOffset",                    3 },
        { "sound_FadeOut",                          1 },
        { "sound_Stop",                             0 },
        { "supervision_Acting",                     1 },
        { "supervision_ExecuteActing",              3 },
        { "supervision_ExecuteActingSub",           3 },
        { "supervision_ExecuteCommon",              1 },
        { "supervision_ExecuteEnter",               1 },
        { "supervision_ExecuteStation",             3 },
        { "supervision_ExecuteStationCommon",       2 },
        { "supervision_ExecuteStationCommonSub",    2 },
        { "supervision_ExecuteStationSub",          3 },
        { "supervision_ExecuteExport",              1 },
        { "supervision_LoadStation",                2 },
        { "supervision_Remove",                     1 },
        { "supervision_RemoveActing",               1 },
        { "supervision_RemoveCommon",               1 },
        { "supervision_SpecialActing",              3 },
        { "supervision_Station",                    1 },
        { "supervision_StationCommon",              1 },
        { "supervision_Suspend",                    1 },
        { "supervision2_SpecialActing",             3 },
        { "Switch",                                 1 },
        { "SwitchDirection",                        1 },
        { "SwitchDirectionLives",                   1 },
        { "SwitchDirectionLives2",                  1 },
        { "SwitchDirectionMark",                    4 },
        { "SwitchDungeonMode",                      1 },
        { "SwitchLives",                            1 },
        { "SwitchRandom",                           1 },
        { "SwitchScenario",                         1 },
        { "SwitchScenarioLevel",                    1 },
        { "SwitchSector",                           0 },
        { "SwitchValue",                            3 },
        { "SwitchVariable",                         3 },
        { "Turn2Direction",                         3 },
        { "Turn2DirectionLives",                    3 },
        { "Turn2DirectionLives2",                   3 },
        { "Turn2DirectionMark",                     8 },
        { "Turn2DirectionTurn",                     3 },
        { "TurnDirection",                          1 },
        { "TurnDirectionLives",                     2 },
        { "TurnDirectionLives2",                    2 },
        { "TurnDirectionMark",                      5 },
        { "Unlock",                                 1 },
        { "Wait",                                   1 },
        { "WaitAnimation",                          0 },
        { "WaitBackEffect",                         0 },
        { "WaitBack2Effect",                        0 },
        { "WaitBgm",                                1 },
        { "WaitBgm2",                               1 },
        { "WaitBgmSignal",                          0 },
        { "WaitEffect",                             0 },
        { "WaitExecuteLives",                       1 },
        { "WaitExecuteObject",                      1 },
        { "WaitExecutePerformer",                   1 },
        { "WaitFadeIn",                             0 },
        { "WaitLockLives",                          2 },
        { "WaitLockObject",                         2 },
        { "WaitLockPerformer",                      2 },
        { "WaitLockSupervision",                    1 },
        { "WaitMe",                                 1 },
        { "WaitMoveCamera",                         0 },
        { "WaitMoveCamera2",                        0 },
        { "WaitRandom",                             2 },
        { "WaitScreenFade",                         0 },
        { "WaitScreenFadeAll",                      0 },
        { "WaitScreen2Fade",                        0 },
        { "WaitSe",                                 1 },
        { "WaitSpecialActing",                      0 },
        { "WaitSubScreen",                          0 },
        { "WaitSubSpecialActing",                   0 },
        { "worldmap_BlinkMark",                     1 },
        { "worldmap_ChangeLevel",                   1 },
        { "worldmap_DeleteArrow",                   0 },
        { "worldmap_MoveCamera",                    1 },
        { "worldmap_OffMessage",                    0 },
        { "worldmap_SetArrow",                      1 },
        { "worldmap_SetCamera",                     1 },
        { "worldmap_SetLevel",                      1 },
        { "worldmap_SetMark",                       1 },
        { "worldmap_SetMessage",                    1 },
        { "worldmap_SetMessagePlace",               1 },
        { "worldmap_SetMode",                       1 },

    } };

//==============================================================================
//  OpCodesInfoListEoS
//==============================================================================
    const std::vector<OpCodeInfoEoS> OpCodesInfoListEoS =
    { {
//      { Opname,                   nbparams,  unk1, unk2, unk3 }
        { "Null",                                   0, -1, 0, 0 },
        { "back_ChangeGround",                      1, -1, 0, 0 },
        { "back_SetBackEffect",                     1, -1, 0, 0 },
        { "back_SetBackScrollOffset",               2, -1, 0, 0 },
        { "back_SetBackScrollSpeed",                2, -1, 0, 0 },
        { "back_SetBanner",                         2,  1, 0, 0 },
        { "back_SetBanner2",                        6,  5, 0, 0 },
        { "back_SetEffect",                         2, -1, 0, 0 },
        { "back_SetDungeonBanner",                  2, -1, 0, 0 },
        { "back_SetGround",                         1, -1, 0, 0 },
        { "back_SetSpecialEpisodeBanner",           2,  1, 0, 0 },
        { "back_SetSpecialEpisodeBanner2",          2,  1, 0, 0 },
        { "back_SetSpecialEpisodeBanner3",          2,  1, 0, 0 },
        { "back_SetTitleBanner",                    2,  1, 0, 0 },
        { "back_SetWeather",                        1, -1, 0, 0 },
        { "back_SetWeatherEffect",                  1, -1, 0, 0 },
        { "back_SetWeatherScrollOffset",            2, -1, 0, 0 },
        { "back_SetWeatherScrollSpeed",             2, -1, 0, 0 },
        { "back2_SetBackEffect",                    1, -1, 0, 0 },
        { "back2_SetBackScrollOffset",              2, -1, 0, 0 },
        { "back2_SetBackScrollSpeed",               2, -1, 0, 0 },
        { "back2_SetData",                          2, -1, 0, 0 },
        { "back2_SetEffect",                        2, -1, 0, 0 },
        { "back2_SetGround",                        1, -1, 0, 0 },
        { "back2_SetMode",                          1, -1, 0, 0 },
        { "back2_SetSpecialActing",                 3, -1, 0, 0 },
        { "back2_SetWeather",                       1, -1, 0, 0 },
        { "back2_SetWeatherEffect",                 1, -1, 0, 0 },
        { "back2_SetWeatherScrollOffset",           2, -1, 0, 0 },
        { "back2_SetWeatherScrollSpeed",            2, -1, 0, 0 },
        { "bgm_FadeOut",                            1, -1, 0, 0 },
        { "bgm_Play",                               1, -1, 0, 0 },
        { "bgm_PlayFadeIn",                         3, -1, 0, 0 },
        { "bgm_Stop",                               0, -1, 0, 0 },
        { "bgm_ChangeVolume",                       2, -1, 0, 0 },
        { "bgm2_FadeOut",                           1, -1, 0, 0 },
        { "bgm2_Play",                              1, -1, 0, 0 },
        { "bgm2_PlayFadeIn",                        3, -1, 0, 0 },
        { "bgm2_Stop",                              0, -1, 0, 0 },
        { "bgm2_ChangeVolume",                      2, -1, 0, 0 },
        { "Branch",                                 3, -1, 1, 0 },
        { "BranchBit",                              3, -1, 1, 0 },
        { "BranchDebug",                            2, -1, 1, 0 },
        { "BranchEdit",                             2, -1, 1, 0 },
        { "BranchExecuteSub",                       2, -1, 1, 0 },
        { "BranchPerformance",                      3, -1, 1, 0 },
        { "BranchScenarioNow",                      4, -1, 1, 0 },
        { "BranchScenarioNowAfter",                 4, -1, 1, 0 },
        { "BranchScenarioNowBefore",                4, -1, 1, 0 },
        { "BranchScenarioAfter",                    4, -1, 1, 0 },
        { "BranchScenarioBefore",                   4, -1, 1, 0 },
        { "BranchSum",                              4, -1, 1, 0 },
        { "BranchValue",                            4, -1, 1, 0 },
        { "BranchVariable",                         4, -1, 1, 0 },
        { "BranchVariation",                        2, -1, 1, 0 },
        { "Call",                                   1, -1, 1, 0 },
        { "CallCommon",                             1, -1, 0, 0 },
        { "camera_Move2Default",                    1, -1, 0, 0 },
        { "camera_Move2MyPosition",                 1, -1, 0, 0 },
        { "camera_Move2Myself",                     1, -1, 0, 0 },
        { "camera_Move2PositionMark",              -1, -1, 0, 0 },
        { "camera_Move2PositionMark",               5, -1, 0, 0 },
        { "camera_Move3Default",                    1, -1, 0, 0 },
        { "camera_Move3MyPosition",                 1, -1, 0, 0 },
        { "camera_Move3Myself",                     1, -1, 0, 0 },
        { "camera_Move3PositionMark",              -1, -1, 0, 0 },
        { "camera_Move3PositionMark",               5, -1, 0, 0 },
        { "camera_MoveDefault",                     1, -1, 0, 0 },
        { "camera_MoveMyPosition",                  1, -1, 0, 0 },
        { "camera_MoveMyself",                      1, -1, 0, 0 },
        { "camera_MovePositionMark",               -1, -1, 0, 0 },
        { "camera_MovePositionMark",                5, -1, 0, 0 },
        { "camera_SetDefault",                      0, -1, 0, 0 },
        { "camera_SetEffect",                       3, -1, 0, 0 },
        { "camera_SetMyPosition",                   0, -1, 0, 0 },
        { "camera_SetMyself",                       0, -1, 0, 0 },
        { "camera_SetPositionMark",                 4, -1, 0, 0 },
        { "camera2_Move2Default",                   1, -1, 0, 0 },
        { "camera2_Move2MyPosition",                1, -1, 0, 0 },
        { "camera2_Move2Myself",                    1, -1, 0, 0 },
        { "camera2_Move2PositionMark",             -1, -1, 0, 0 },
        { "camera2_Move2PositionMark",              5, -1, 0, 0 },
        { "camera2_Move3Default",                   1, -1, 0, 0 },
        { "camera2_Move3MyPosition",                1, -1, 0, 0 },
        { "camera2_Move3Myself",                    1, -1, 0, 0 },
        { "camera2_Move3PositionMark",             -1, -1, 0, 0 },
        { "camera2_Move3PositionMark",              5, -1, 0, 0 },
        { "camera2_MoveDefault",                    1, -1, 0, 0 },
        { "camera2_MoveMyPosition",                 1, -1, 0, 0 },
        { "camera2_MoveMyself",                     1, -1, 0, 0 },
        { "camera2_MovePositionMark",              -1, -1, 0, 0 },
        { "camera2_MovePositionMark",               5, -1, 0, 0 },
        { "camera2_SetDefault",                     0, -1, 0, 0 },
        { "camera2_SetEffect",                      3, -1, 0, 0 },
        { "camera2_SetMyPosition",                  0, -1, 0, 0 },
        { "camera2_SetMyself",                      0, -1, 0, 0 },
        { "camera2_SetPositionMark",                4, -1, 0, 0 },
        { "CancelCut",                              0, -1, 1, 0 },
        { "CancelRecoverCommon",                    1, -1, 1, 0 },
        { "Case",                                   2, -1, 1, 0 },
        { "CaseMenu",                               2,  0, 1, 0 },
        { "CaseMenu2",                              2, -1, 1, 0 },
        { "CaseScenario",                           3, -1, 1, 0 },
        { "CaseText",                               2,  1, 0, 0 },
        { "CaseValue",                              3, -1, 1, 0 },
        { "CaseVariable",                           3, -1, 1, 0 },
        { "debug_Assert",                           1, -1, 0, 0 },
        { "debug_Print",                            1, -1, 0, 0 },
        { "debug_PrintFlag",                        2, -1, 0, 0 },
        { "debug_PrintScenario",                    2, -1, 0, 0 },
        { "DefaultText",                            1,  0, 0, 0 },
        { "Destroy",                                0, -1, 0, 0 },
        { "End",                                    0, -1, 0, 0 },
        { "EndAnimation",                           0, -1, 0, 0 },
        { "ExecuteActing",                          1, -1, 0, 0 },
        { "ExecuteCommon",                          2, -1, 0, 0 },
        { "flag_CalcBit",                           3, -1, 0, 0 },
        { "flag_CalcValue",                         3, -1, 0, 0 },
        { "flag_CalcVariable",                      3, -1, 0, 0 },
        { "flag_Clear",                             1, -1, 0, 0 },
        { "flag_Initial",                           1, -1, 0, 0 },
        { "flag_Set",                               2, -1, 0, 0 },
        { "flag_ResetDungeonResult",                0, -1, 0, 0 },
        { "flag_ResetScenario",                     1, -1, 0, 0 },
        { "flag_SetAdventureLog",                   1, -1, 0, 0 },
        { "flag_SetDungeonMode",                    2, -1, 0, 0 },
        { "flag_SetDungeonResult",                  2, -1, 0, 0 },
        { "flag_SetPerformance",                    2, -1, 0, 0 },
        { "flag_SetScenario",                       3, -1, 0, 0 },
        { "Flash",                                  0, -1, 0, 0 },
        { "Hold",                                   0, -1, 0, 0 },
        { "item_GetVariable",                       2, -1, 0, 0 },
        { "item_Set",                               3, -1, 0, 0 },
        { "item_SetTableData",                      2, -1, 0, 0 },
        { "item_SetVariable",                       2, -1, 0, 0 },
        { "Jump",                                   1, -1, 1, 0 },
        { "JumpCommon",                             1, -1, 0, 0 },
        { "lives",                                  1, -1, 0, 0 },
        { "LoadPosition",                           1, -1, 0, 0 },
        { "Lock",                                   1, -1, 0, 0 },
        { "main_EnterAdventure",                    2, -1, 0, 0 },
        { "main_EnterDungeon",                      2, -1, 0, 0 },
        { "main_EnterGround",                       2, -1, 0, 0 },
        { "main_EnterGroundMulti",                  3, -1, 0, 0 },
        { "main_EnterRescueUser",                   1, -1, 0, 0 },
        { "main_EnterTraining",                     2, -1, 0, 0 },
        { "main_EnterTraining2",                    2, -1, 0, 0 },
        { "main_SetGround",                         1, -1, 0, 0 },
        { "me_Play",                                1, -1, 0, 0 },
        { "me_Stop",                                0, -1, 0, 0 },
        { "message_Close",                          0, -1, 0, 0 },
        { "message_CloseEnforce",                   0, -1, 0, 0 },
        { "message_Explanation",                    1,  0, 0, 0 },
        { "message_FacePositionOffset",             2, -1, 0, 0 },
        { "message_ImitationSound",                 1,  0, 0, 0 },
        { "message_KeyWait",                        0, -1, 0, 0 },
        { "message_Mail",                           1,  0, 0, 0 },
        { "message_Menu",                           1, -1, 0, 0 },
        { "message_Monologue",                      1,  0, 0, 0 },
        { "message_Narration",                      2,  1, 0, 0 },
        { "message_Notice",                         1,  0, 0, 0 },
        { "message_EmptyActor",                     0, -1, 0, 0 },
        { "message_ResetActor",                     0, -1, 0, 0 },
        { "message_SetActor",                       1, -1, 0, 0 },
        { "message_SetFace",                        3, -1, 0, 0 },
        { "message_SetFaceEmpty",                   3, -1, 0, 0 },
        { "message_SetFaceOnly",                    3, -1, 0, 0 },
        { "message_SetFacePosition",                1, -1, 0, 0 },
        { "message_SetWaitMode",                    2, -1, 0, 0 },
        { "message_SpecialTalk",                    1, -1, 0, 0 },
        { "message_SwitchMenu",                     2, -1, 0, 0 },
        { "message_SwitchMenu2",                    3, -1, 0, 0 },
        { "message_SwitchMonologue",                1, -1, 0, 0 },
        { "message_SwitchTalk",                     1, -1, 0, 0 },
        { "message_Talk",                           1,  0, 0, 0 },
        { "Move2Position",                          3, -1, 0, 0 },
        { "Move2PositionLives",                     2, -1, 0, 0 },
        { "Move2PositionMark",                     -1, -1, 0, 0 },
        { "Move2PositionMark",                      5, -1, 0, 0 },
        { "Move2PositionOffset",                   -1, -1, 0, 0 },
        { "Move2PositionOffset",                    3, -1, 0, 0 },
        { "Move2PositionOffsetRandom",              3, -1, 0, 0 },
        { "Move3Position",                          3, -1, 0, 0 },
        { "Move3PositionLives",                     2, -1, 0, 0 },
        { "Move3PositionMark",                     -1, -1, 0, 0 },
        { "Move3PositionMark",                      5, -1, 0, 0 },
        { "Move3PositionOffset",                   -1, -1, 0, 0 },
        { "Move3PositionOffset",                    3, -1, 0, 0 },
        { "Move3PositionOffsetRandom",              3, -1, 0, 0 },
        { "MoveDirection",                          3, -1, 0, 0 },
        { "MoveHeight",                             2, -1, 0, 0 },
        { "MovePosition",                           3, -1, 0, 0 },
        { "MovePositionLives",                      2, -1, 0, 0 },
        { "MovePositionLivesTime",                  3, -1, 0, 0 },
        { "MovePositionMark",                      -1, -1, 0, 0 },
        { "MovePositionMark",                       5, -1, 0, 0 },
        { "MovePositionMarkTime",                   6, -1, 0, 0 },
        { "MovePositionOffset",                    -1, -1, 0, 0 },
        { "MovePositionOffset",                     3, -1, 0, 0 },
        { "MoveSpecial",                            3, -1, 0, 0 },
        { "MoveTurn",                               3, -1, 0, 0 },
        { "object",                                 1, -1, 0, 0 },
        { "PauseEffect",                            1, -1, 0, 0 },
        { "performer",                              1, -1, 0, 0 },
        { "ProcessSpecial",                         3, -1, 0, 0 },
        { "PursueTurnLives",                        4, -1, 0, 0 },
        { "PursueTurnLives2",                       4, -1, 0, 0 },
        { "ResetAttribute",                         1, -1, 0, 0 },
        { "ResetFunctionAttribute",                 1, -1, 0, 0 },
        { "ResetHitAttribute",                      1, -1, 0, 0 },
        { "ResetOutputAttribute",                   1, -1, 0, 0 },
        { "ResetReplyAttribute",                    1, -1, 0, 0 },
        { "ResumeEffect",                           1, -1, 0, 0 },
        { "Return",                                 0, -1, 0, 0 },
        { "SavePosition",                           1, -1, 0, 0 },
        { "screen_FadeChange",                      4, -1, 0, 0 },
        { "screen_FadeChangeAll",                   4, -1, 0, 0 },
        { "screen_FadeIn",                          2, -1, 0, 0 },
        { "screen_FadeInAll",                       2, -1, 0, 0 },
        { "screen_FadeOut",                         2, -1, 0, 0 },
        { "screen_FadeOutAll",                      2, -1, 0, 0 },
        { "screen_FlushChange",                     8, -1, 0, 0 },
        { "screen_FlushIn",                         6, -1, 0, 0 },
        { "screen_FlushOut",                        6, -1, 0, 0 },
        { "screen_WhiteChange",                     4, -1, 0, 0 },
        { "screen_WhiteChangeAll",                  4, -1, 0, 0 },
        { "screen_WhiteIn",                         2, -1, 0, 0 },
        { "screen_WhiteInAll",                      2, -1, 0, 0 },
        { "screen_WhiteOut",                        2, -1, 0, 0 },
        { "screen_WhiteOutAll",                     2, -1, 0, 0 },
        { "screen2_FadeChange",                     4, -1, 0, 0 },
        { "screen2_FadeChangeAll",                  4, -1, 0, 0 },
        { "screen2_FadeIn",                         2, -1, 0, 0 },
        { "screen2_FadeInAll",                      2, -1, 0, 0 },
        { "screen2_FadeOut",                        2, -1, 0, 0 },
        { "screen2_FadeOutAll",                     2, -1, 0, 0 },
        { "screen2_FlushChange",                    8, -1, 0, 0 },
        { "screen2_FlushIn",                        6, -1, 0, 0 },
        { "screen2_FlushOut",                       6, -1, 0, 0 },
        { "screen2_WhiteChange",                    4, -1, 0, 0 },
        { "screen2_WhiteChangeAll",                 4, -1, 0, 0 },
        { "screen2_WhiteIn",                        2, -1, 0, 0 },
        { "screen2_WhiteInAll",                     2, -1, 0, 0 },
        { "screen2_WhiteOut",                       2, -1, 0, 0 },
        { "screen2_WhiteOutAll",                    2, -1, 0, 0 },
        { "se_ChangePan",                           3, -1, 0, 0 },
        { "se_ChangeVolume",                        3, -1, 0, 0 },
        { "se_FadeOut",                             2, -1, 0, 0 },
        { "se_Play",                                1, -1, 0, 0 },
        { "se_PlayFull",                            3, -1, 0, 0 },
        { "se_PlayPan",                             2, -1, 0, 0 },
        { "se_PlayVolume",                          2, -1, 0, 0 },
        { "se_Stop",                                1, -1, 0, 0 },
        { "SetAnimation",                           1, -1, 0, 0 },
        { "SetAttribute",                           1, -1, 0, 0 },
        { "SetBlink",                               2, -1, 0, 0 },
        { "SetDirection",                           1, -1, 0, 0 },
        { "SetDirectionLives",                      2, -1, 0, 0 },
        { "SetEffect",                              2, -1, 0, 0 },
        { "SetFunctionAttribute",                   1, -1, 0, 0 },
        { "SetHeight",                              1, -1, 0, 0 },
        { "SetHitAttribute",                        1, -1, 0, 0 },
        { "SetMoveRange",                           6, -1, 0, 0 },
        { "SetOutputAttribute",                     1, -1, 0, 0 },
        { "SetPosition",                            2, -1, 0, 0 },
        { "SetPositionInitial",                     0, -1, 0, 0 },
        { "SetPositionLives",                       1, -1, 0, 0 },
        { "SetPositionMark",                        4, -1, 0, 0 },
        { "SetPositionOffset",                      2, -1, 0, 0 },
        { "SetPositionOffsetRandom",                2, -1, 0, 0 },
        { "SetReplyAttribute",                      1, -1, 0, 0 },
        { "SetupOutputAttributeAndAnimation",       3, -1, 0, 0 },
        { "Slide2Position",                         3, -1, 0, 0 },
        { "Slide2PositionLives",                    2, -1, 0, 0 },
        { "Slide2PositionMark",                    -1, -1, 0, 0 },
        { "Slide2PositionMark",                     5, -1, 0, 0 },
        { "Slide2PositionOffset",                  -1, -1, 0, 0 },
        { "Slide2PositionOffset",                   3, -1, 0, 0 },
        { "Slide2PositionOffsetRandom",             3, -1, 0, 0 },
        { "Slide3Position",                         3, -1, 0, 0 },
        { "Slide3PositionLives",                    2, -1, 0, 0 },
        { "Slide3PositionMark",                    -1, -1, 0, 0 },
        { "Slide3PositionMark",                     5, -1, 0, 0 },
        { "Slide3PositionOffset",                  -1, -1, 0, 0 },
        { "Slide3PositionOffset",                   3, -1, 0, 0 },
        { "Slide3PositionOffsetRandom",             3, -1, 0, 0 },
        { "SlideHeight",                            2, -1, 0, 0 },
        { "SlidePosition",                          3, -1, 0, 0 },
        { "SlidePositionLives",                     2, -1, 0, 0 },
        { "SlidePositionLivesTime",                 3, -1, 0, 0 },
        { "SlidePositionMark",                     -1, -1, 0, 0 },
        { "SlidePositionMark",                      5, -1, 0, 0 },
        { "SlidePositionMarkTime",                  6, -1, 0, 0 },
        { "SlidePositionOffset",                   -1, -1, 0, 0 },
        { "SlidePositionOffset",                    3, -1, 0, 0 },
        { "sound_FadeOut",                          1, -1, 0, 0 },
        { "sound_Stop",                             0, -1, 0, 0 },
        { "StopAnimation",                          0, -1, 0, 0 },
        { "supervision_Acting",                     1, -1, 0, 0 },
        { "supervision_ActingInvisible",            1, -1, 0, 0 },
        { "supervision_ExecuteActing",              3, -1, 0, 0 },
        { "supervision_ExecuteActingSub",           3, -1, 0, 0 },
        { "supervision_ExecuteCommon",              1, -1, 0, 0 },
        { "supervision_ExecuteEnter",               1, -1, 0, 0 },
        { "supervision_ExecuteStation",             3, -1, 0, 0 },
        { "supervision_ExecuteStationCommon",       2, -1, 0, 0 },
        { "supervision_ExecuteStationCommonSub",    2, -1, 0, 0 },
        { "supervision_ExecuteStationSub",          3, -1, 0, 0 },
        { "supervision_ExecuteExport",              1, -1, 0, 0 },
        { "supervision_ExecuteExportSub",           1, -1, 0, 0 },
        { "supervision_LoadStation",                2, -1, 0, 0 },
        { "supervision_Remove",                     1, -1, 0, 0 },
        { "supervision_RemoveActing",               1, -1, 0, 0 },
        { "supervision_RemoveCommon",               1, -1, 0, 0 },
        { "supervision_SpecialActing",              3, -1, 0, 0 },
        { "supervision_Station",                    1, -1, 0, 0 },
        { "supervision_StationCommon",              1, -1, 0, 0 },
        { "supervision_Suspend",                    1, -1, 0, 0 },
        { "supervision2_SpecialActing",             3, -1, 0, 0 },
        { "Switch",                                 1, -1, 0, 0 },
        { "SwitchDirection",                        1, -1, 0, 0 },
        { "SwitchDirectionLives",                   1, -1, 0, 0 },
        { "SwitchDirectionLives2",                  1, -1, 0, 0 },
        { "SwitchDirectionMark",                    4, -1, 0, 0 },
        { "SwitchDungeonMode",                      1, -1, 0, 0 },
        { "SwitchLives",                            1, -1, 0, 0 },
        { "SwitchRandom",                           1, -1, 0, 0 },
        { "SwitchScenario",                         1, -1, 0, 0 },
        { "SwitchScenarioLevel",                    1, -1, 0, 0 },
        { "SwitchSector",                           0, -1, 0, 0 },
        { "SwitchValue",                            3, -1, 0, 0 },
        { "SwitchVariable",                         3, -1, 0, 0 },
        { "Turn2Direction",                         3, -1, 0, 0 },
        { "Turn2DirectionLives",                    3, -1, 0, 0 },
        { "Turn2DirectionLives2",                   3, -1, 0, 0 },
        { "Turn2DirectionMark",                     8, -1, 0, 0 },
        { "Turn2DirectionTurn",                     3, -1, 0, 0 },
        { "Turn3",                                  4, -1, 0, 0 },
        { "TurnDirection",                          1, -1, 0, 0 },
        { "TurnDirectionLives",                     2, -1, 0, 0 },
        { "TurnDirectionLives2",                    2, -1, 0, 0 },
        { "TurnDirectionMark",                      5, -1, 0, 0 },
        { "Unlock",                                 1, -1, 0, 0 },
        { "Wait",                                   1, -1, 0, 0 },
        { "WaitAnimation",                          0, -1, 0, 0 },
        { "WaitBackEffect",                         0, -1, 0, 0 },
        { "WaitBack2Effec",                         0, -1, 0, 0 },
        { "WaitBgm",                                1, -1, 0, 0 },
        { "WaitBgm2",                               1, -1, 0, 0 },
        { "WaitBgmSignal",                          0, -1, 0, 0 },
        { "WaitEffect",                             0, -1, 0, 0 },
        { "WaitEndAnimation",                       0, -1, 0, 0 },
        { "WaitExecuteLives",                       1, -1, 0, 0 },
        { "WaitExecuteObject",                      1, -1, 0, 0 },
        { "WaitExecutePerformer",                   1, -1, 0, 0 },
        { "WaitFadeIn",                             0, -1, 0, 0 },
        { "WaitLockLives",                          2, -1, 0, 0 },
        { "WaitLockObject",                         2, -1, 0, 0 },
        { "WaitLockPerformer",                      2, -1, 0, 0 },
        { "WaitLockSupervision",                    1, -1, 0, 0 },
        { "WaitMe",                                 1, -1, 0, 0 },
        { "WaitMoveCamera",                         0, -1, 0, 0 },
        { "WaitMoveCamera2",                        0, -1, 0, 0 },
        { "WaitRandom",                             2, -1, 0, 0 },
        { "WaitScreenFade",                         0, -1, 0, 0 },
        { "WaitScreenFadeAll",                      0, -1, 0, 0 },
        { "WaitScreen2Fade",                        0, -1, 0, 0 },
        { "WaitSe",                                 1, -1, 0, 0 },
        { "WaitSpecialActing",                      0, -1, 0, 0 },
        { "WaitSubScreen",                          0, -1, 0, 0 },
        { "WaitSubSpecialActing",                   0, -1, 0, 0 },
        { "worldmap_BlinkMark",                     1, -1, 0, 0 },
        { "worldmap_ChangeLevel",                   1, -1, 0, 0 },
        { "worldmap_DeleteArrow",                   0, -1, 0, 0 },
        { "worldmap_MoveCamera",                    1, -1, 0, 0 },
        { "worldmap_OffMessage",                    0, -1, 0, 0 },
        { "worldmap_SetArrow",                      1, -1, 0, 0 },
        { "worldmap_SetCamera",                     1, -1, 0, 0 },
        { "worldmap_SetLevel",                      1, -1, 0, 0 },
        { "worldmap_SetMark",                       1, -1, 0, 0 },
        { "worldmap_SetMessage",                    1,  0, 0, 0 },
        { "worldmap_SetMessagePlace",               1, -1, 0, 0 },
        { "worldmap_SetMode",                       1, -1, 0, 0 },
    } };


};